com.dipcoin.db.services.DataSource.host=stage-db-new.cf2ik20ms4wt.ap-south-1.rds.amazonaws.com:3306
com.dipcoin.db.services.DataSource.user=dipcoindb 
com.dipcoin.db.services.DataSource.password=O5taD1pC0in
com.dipcoin.db.services.DataSource.db=dipcoin
