com.dipcoin.partner.utils.PartnerKeyStore.keystorepath=classpath:keys/partner_keys.p12
#com.dipcoin.partner.utils.PartnerKeyStore.keystorepass=ENC(anyRBk6Ea2m2Mc6b6rpVl4ufrJoRG7rA)
#com.dipcoin.partner.utils.PartnerKeyStore.keystorekeypass=ENC(anyRBk6Ea2m2Mc6b6rpVl4ufrJoRG7rA)
com.dipcoin.partner.utils.PartnerKeyStore.keystorepass=ENC(pJd8cy5UzvxicpY492jMplKPtfCKdIws)
com.dipcoin.partner.utils.PartnerKeyStore.keystorekeypass=ENC(pJd8cy5UzvxicpY492jMplKPtfCKdIws)
com.dipcoin.partner.toll.compliance.test.check408 = false
com.dipcoin.partner.toll.compliance.test.check400 = false
com.dipcoin.partner.toll.mappingOfVehicleVC6=VC8
