com.dipcoin.recharge.utils.RechargeConfigurations.PaymentMode=Wallet
com.dipcoin.recharge.utils.RechargeConfigurations.PaymentName=WalletName|MobileNo
com.dipcoin.recharge.utils.RechargeConfigurations.ChannelName=IP,IMEI,OS,APP
com.dipcoin.recharge.utils.RechargeConfigurations.ChannelNameAgt=INITIATING_CHANNEL,MOBILE,GEOCODE,POSTAL_CODE,TERMINAL_ID
com.dipcoin.recharge.utils.RechargeConfigurations.ChannelNameBankBranch=MOBILE,GEOCODE,POSTAL_CODE,IFSC
com.dipcoin.recharge.utils.RechargeConfigurations.ChannelNameInt=IP,MAC
com.dipcoin.recharge.utils.RechargeConfigurations.PaymentNameCash=Remarks
com.dipcoin.recharge.utils.RechargeConfigurations.PaymentNameAccountTransfer=IFSC|AccountNo

