#com.dipcoin.recharge.utils.RechargeConfigurations.IPAddress=13.232.21.143
com.dipcoin.recharge.utils.RechargeConfigurations.IPAddress=3.111.101.21
com.dipcoin.recharge.utils.RechargeConfigurations.RequestTimeOut=36000
com.dipcoin.recharge.utils.RechargeConfigurations.MerchantCode=BNT
com.dipcoin.recharge.utils.RechargeConfigurations.StoreCode=BNT_01
com.dipcoin.recharge.utils.RechargeConfigurations.UserName=BNT_01
com.dipcoin.recharge.utils.RechargeConfigurations.UserPass=BNT_01
com.dipcoin.recharge.utils.RechargeConfigurations.AgentId=EU01EU02000000000001
com.dipcoin.recharge.utils.RechargeConfigurations.OffUsPay=NO
com.dipcoin.recharge.utils.RechargeConfigurations.Salt=Os3dcl82
com.dipcoin.recharge.utils.RechargeConfigurations.ChannelCode=MOBB
#com.dipcoin.recharge.utils.RechargeConfigurations.ChannelValue=13.232.21.143,448674528976410,Android,FEDMOB3.111.101.21
com.dipcoin.recharge.utils.RechargeConfigurations.ChannelValue=3.111.101.21,448674528976410,Android,FEDMOB
com.dipcoin.recharge.utils.RechargeConfigurations.PaymentValue=U/grWbrouviK8sBh68DRgA==
com.dipcoin.recharge.utils.RechargeConfigurations.EuronetHost=103.19.217.55
com.dipcoin.recharge.utils.RechargeConfigurations.BBPSHost=103.19.217.55
com.dipcoin.recharge.utils.RechargeConfigurations.GetBBPSUrl=enserviceAES256/API/EnService
com.dipcoin.recharge.utils.RechargeConfigurations.GetValidationUrl=EN_Service2.1/API/Validate
com.dipcoin.recharge.utils.RechargeConfigurations.GetServiceUrl=EN_Service2.1/API/Service
com.dipcoin.recharge.utils.RechargeConfigurations.GetStatusUrl=EN_Service2.1/API/Status
com.dipcoin.recharge.utils.RechargeConfigurations.GetBalanceUrl=EN_Service2.1/API/Balance
com.dipcoin.recharge.utils.RechargeConfigurations.RechargePlanHost=epayuat.eftapme.com
com.dipcoin.recharge.utils.RechargeConfigurations.RechargePlanUrl=RechargePlanApi/RechargePlans.aspx
