com.dipcoin.partner.toll.connect.npci=false
com.dipcoin.partner.toll.api.url.syncTimeRequest = https://cm.npci.org.in:443/syncTimeRequest
com.dipcoin.partner.toll.api.url.getExceptionList = https://cm.npci.org.in:443/getExceptionList
com.dipcoin.partner.toll.api.url.queryException = https://cm.npci.org.in:443/queryException
com.dipcoin.partner.toll.api.url.manageTags = https://cm.npci.org.in:443/manageTags
com.dipcoin.partner.toll.api.url.requestDetail = https://cm.npci.org.in:443/requestDetail
com.dipcoin.partner.toll.api.url.requestDetailIHMCL = https://cm.npci.org.in:443/requestDetailIHMCL
com.dipcoin.partner.toll.api.url.manageException = https://cm.npci.org.in:443/manageException
com.dipcoin.partner.toll.api.url.responsePayService = https://cm.npci.org.in:443/responsePayService
com.dipcoin.partner.toll.bank.info = Central Bank Of India~brio~508571~https://192.168.6.190/,THRISSUR DISTRICT CO - OPERATIVE BANK~tdxb~607541~https://192.168.6.191/,The jalgaon peoples co-operative Bank LTD~jpxb~500005~https://192.168.6.189/,ANDHRA PRADESH GRAMEENA VIKAS BANK~AGXB~508920~https://10.1.31.36/
com.dipcoin.partner.toll.bankKeystore.path = /home/bitnami/bankKeyStore/bank.p12
com.dipcoin.partner.toll.bankKeystore.password = mQgnl5+Fh9bDRa6lMLMuBFw4hav/i/lG
com.dipcoin.partner.toll.bank.info.nameAndIin = Airtel~607569,BOB~652151,City Union Bank~607949,Equitas Bank~652402,IDBI Bank~607095,IDFC First Bank~608116,Indian Bank~607016,IndusInd Bank (IHMCL Tags)~608266,Kotak Mahindra Bank~607469,Kotak Mahindra Bank World Line~607421,KVB~607100,PayTm Payments Bank~608032,PNB~607859,Saraswat bank~652150,SBI~606986,Union Bank~606992,Yes Bank~652210,ICICI Bank~607417,AXIS BANK~607529,IHMCL~222222,IHMCL~222223,IndusInd~607189,HDFC~607318,Central Bank Of India~607003,TDCB~607916,JPCB~607134
com.dipcoin.partner.toll.api.url.reqVehicleDetails = /requestVechlDetail

# NETC NPCI Health check IPs for Active-Active Set up
com.dipcoin.partner.toll.api.netcHealthCheck.ips = 192.168.63.33,192.168.62.53
com.dipcoin.partner.toll.api.netcHealthCheck.port = 443
com.dipcoin.partner.toll.api.netcHealthCheck.endPoint = /api-admin/ping

com.dipcoin.partner.gstin.Url=myretailware.azurewebsites.net/service/license.asmx?op=GSTIN_TaxPayerSearch
com.dipcoin.partner.gstin.LoginUserName=ajit
com.dipcoin.partner.gstin.LoginPassword=MWj91icDevuUyxJneiQG0A==
com.dipcoin.partner.gstin.SoftwareID=1
com.dipcoin.partner.gstin.ClientID=47112
com.dipcoin.partner.gstin.HDNumber=DF086700-7EF3-4119-9DAF-65DB9AFC475D
com.dipcoin.partner.gstin.MachineName=OSTA-HOST
com.dipcoin.partner.gstin.UserName=jaideep@ostaapp.com
com.dipcoin.partner.gstin.IsPipeResponse=No

#dipcoin internal call properties
com.dipcoin.partner.config.dipcoinInternal.topupApi=https://api-test.ostaapp.com/api/v1/oauth2/internaltopup
com.dipcoin.partner.config.dipcoinInternal.processOsta=https://api-test.ostaapp.com/api/v1/oauth2/internalprocess/osta
com.dipcoin.partner.config.dipcoinInternal.isProxy=false
com.dipcoin.partner.config.dipcoinInternal.port=0
com.dipcoin.partner.config.dipcoinInternal.host=