user.get.byid =  select * from CoreBank where Status = '0' and BankID = :bankId and AuthType = :authType and AuthenticationID = :authenticationId
	
user.insert.account.details = INSERT INTO DipcoinAccount (CoreBankID, BankID, IFSCCode, AccountNumber, AuthenticationID, AccountStatus,AccountStatusDesc, AmountOnHold, AvailableAmount, BankTransactionReferenceNum, DipcoinRequestTime ) \
							VALUES (:coreBankId, :bankId, :ifscCode, :accountNumber, :authenticationId, :accountStatus, :accountStatusDesc, :amountOnHold, :availableAmount, :bankRefNumber, :dipcoinReqTime )

user.update.account.details = UPDATE DipcoinAccount set BankUID = :bankUID, AccountStatus = :accountStatus, AccountStatusDesc = :accountStatusDesc, AmountOnHold = :amountOnHold, \
							AvailableAmount = :availableAmount, AttemptCount = :attempt, BankTransactionReferenceNum = :bankRefNumber, DipcoinRequestTime = :dipcoinReqTime \
							WHERE BankTransactionReferenceNum =  :bankTransactionReferenceNumber
	
user.add.account = INSERT INTO CoreBank (BankID, IFSCCode, AccountNumber, TotalAmount, AmountOnHold, AvailableAmount, AuthType, AuthenticationID,  Password, OTP, OTPVerified) \
							VALUES (:bankId, :ifscCode, :accountNumber, :totalAmount, :amountOnHold, :availableAmount, :authType, :authenticationID, :password, :otp, :otpVerified )
								
coreBank.count.account = SELECT COUNT(*) from CoreBank where Status = '0' and BankID = :bankID and AuthType = :authType and AuthenticationID = :authenticationID
				
user.get.all = select * from dipcoinAccount where AccountStatus = :status
				
otp.bybanktransactionreferencenumber =  select * from CoreBank where Status = 0 and id = (select CoreBankID from \
									DipcoinAccount where AccountStatus !=2 and BankTransactionReferenceNum =  :bankTransactionReferenceNumber)	
				
user.update.bankuid = UPDATE CoreBank SET OTPVerified = :otpVerified, \
				OTPVerificationTime = :otpVerificationTime, \
				OTPVerifyAttempt = :otpVerifyAttempt \
				where id = (select CoreBankID from \
				DipcoinAccount where BankTransactionReferenceNum =  :bankTransactionReferenceNumber)
				
dipcoinaccount.count.account = SELECT * from DipcoinAccount where AccountStatus = '0' and BankID = :bankId and ( AuthenticationID = :reqId || BankTransactionReferenceNum = :reqId)