package com.dipcoin.api.model;

import com.dipcoin.api.filter.HttpServletContext;
import io.swagger.annotations.ApiModelProperty;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.experimental.Accessors;

@NoArgsConstructor
@Accessors(chain = true)
@Setter
@Getter
public class AutoGenerateDipcoinRequest extends CustomerDipcoinRequest {

  @ApiModelProperty(required = true)
  private Integer parentDipcoinId;
  @ApiModelProperty(required = true)
  private Integer accountId;

  @Override
  public boolean validate(HttpServletContext httpServletContext) {
    return true;
  }
}
