/**
 *
 */
package com.dipcoin.api.resource;

import java.awt.image.BufferedImage;
import java.math.BigDecimal;
import java.util.List;
import org.apache.commons.lang3.StringUtils;
import org.apache.commons.lang3.math.NumberUtils;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.joda.time.DateTime;
import org.joda.time.DateTimeZone;
import org.springframework.amqp.rabbit.core.RabbitTemplate;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.context.annotation.Lazy;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;
import com.dipcoin.api.commons.APIException;
import com.dipcoin.api.commons.HeaderCode;
import com.dipcoin.api.filter.HttpServletContext;
import com.dipcoin.api.model.AutoGenerateDipcoinRequest;
import com.dipcoin.api.model.CustomerDipcoinRequest;
import com.dipcoin.commons.CoreUtils;
import com.dipcoin.commons.LogFormatter;
import com.dipcoin.commons.qrcode.Decorator;
import com.dipcoin.db.services.CustomerDBService;
import com.dipcoin.db.services.DipcoinDBService;
import com.dipcoin.db.services.commons.DBConstants;
import com.dipcoin.db.services.commons.DBConstants.BooleanStatus;
import com.dipcoin.db.services.commons.DBConstants.DipcoinTransactionType;
import com.dipcoin.db.services.commons.DBConstants.DipcoinTransactionsStatus;
import com.dipcoin.db.services.commons.DBConstants.TransactionSource;
import com.dipcoin.db.services.model.Bank;
import com.dipcoin.db.services.model.CustomerAccount;
import com.dipcoin.db.services.model.Dipcoin;
import com.dipcoin.db.services.model.DipcoinTransaction;
import com.dipcoin.db.services.model.User;
import com.dipcoin.metrics.DipcoinMetricRegistry;
import com.fasterxml.jackson.databind.ObjectMapper;

/**
*
*/
@Component("dipcoinResource")
@Transactional(rollbackFor = {Exception.class, APIException.class},
   propagation = Propagation.REQUIRES_NEW)
public class DipcoinResource {

 @Autowired
 private DipcoinDBService coinDBService;

 @Autowired
 RabbitTemplate asyncRequestAmqpTemplate;
 
 @Autowired
 private InternalResource internalResource;
 
 @Autowired
 @Qualifier("com.dipcoin.metrics.DipcoinMetricRegistry")
 private DipcoinMetricRegistry dipcoinMetricRegistry;

 @Autowired
 @Lazy
 protected HttpServletContext httpServletContext;
 
 @Autowired
 private CustomerDBService customerDBService;
 
 public void setHttpServletContext(HttpServletContext httpServletContext) {
	    this.httpServletContext = httpServletContext;
	  }

	  private static final Logger LOG = LogManager.getLogger(DipcoinResource.class);
	  private final static ObjectMapper objectMapper = new ObjectMapper();
	  // @TODO - configure this via config
	  //protected static boolean encryptDipcoin = false;

	  // @TODO - move to a commons class
	  private Decorator<BufferedImage> logo_125_125 = null;

	  public Decorator<BufferedImage> getLogoImageDecorator() {
	    return this.logo_125_125;
	  }
 
 // shifted this method in this resource as @transactional was 
	public Dipcoin generateDipcoin(final CustomerDipcoinRequest createReq, final User user,
			final CustomerAccount account, final Boolean isDuplicate) {

		Integer ttl = 0;

		// generate token + additional metadata
		String token = null;
		if(isDuplicate) {
			token = getUniqueToken(user);
		}else {
			token = CoreUtils.generateDipcoinToken();
		}
					
		LOG.debug(LogFormatter.instance(httpServletContext.getTraceId()).data("Phone", user.getPhone())
				.data("Coin", token).format());

		// create dipcoin in DB
		Dipcoin dcoin = new Dipcoin();
		dcoin.setUser(user);
		dcoin.setCoin(token);
		dcoin.setAmount(createReq.getAmount());
		dcoin.setCustomerAccount(account);
		dcoin.setUsageType(createReq.getUsageType());
		dcoin.setUsageCategory(createReq.getUsageCategory());
		if (!StringUtils.isEmpty(createReq.getUsageCategory()))
			dcoin.setUsageCategory(createReq.getUsageCategory());
		if (createReq.getUsageType() == null
				|| createReq.getUsageType() == DBConstants.DipcoinUsageType.GENERIC.value())
			dcoin.setUsageType(DBConstants.DipcoinUsageType.GENERIC.value());
		else if (createReq.getUsageType() == DBConstants.DipcoinUsageType.ATM.value())
			dcoin.setUsageType(DBConstants.DipcoinUsageType.ATM.value());
		else if (createReq.getUsageType() == DBConstants.DipcoinUsageType.TRANSFER.value())
			dcoin.setUsageType(DBConstants.DipcoinUsageType.TRANSFER.value());
		else if (createReq.getUsageType() == DBConstants.DipcoinUsageType.BILL_PAYMENTS_RECHARGES.value())
			dcoin.setUsageType(DBConstants.DipcoinUsageType.BILL_PAYMENTS_RECHARGES.value());
		else if (createReq.getUsageType() == DBConstants.DipcoinUsageType.PURCHASE.value())
			dcoin.setUsageType(DBConstants.DipcoinUsageType.PURCHASE.value());
		else if (createReq.getUsageType() == DBConstants.DipcoinUsageType.RESTRICTED_BBPS_CASH.value())
          dcoin.setUsageType(DBConstants.DipcoinUsageType.RESTRICTED_BBPS_CASH.value());
		 else if (createReq.getUsageType() == DBConstants.DipcoinUsageType.RESTRICTED_BBPS_FUND_TRANSFER.value())
	          dcoin.setUsageType(DBConstants.DipcoinUsageType.RESTRICTED_BBPS_FUND_TRANSFER.value());
		
		dcoin.setClientTransactionId(httpServletContext.getClientTransactionId());

		Bank bank = account.getBank();

		// compute dipcoin TTL.
		if (DBConstants.DipcoinUsageType.TOLL.value() == createReq.getUsageType()
				|| DBConstants.BankType.VIRTUAL_BANK.value() == bank.getType()
				|| DBConstants.DipcoinUsageType.FEE.value() == createReq.getUsageType()
				|| DBConstants.DipcoinUsageType.DEPOSIT.value() == createReq.getUsageType()) {

			ttl = createReq.getTtlInHrs() != null
					? (createReq.getTtlInHrs() <= DBConstants.DIPCOIN_ONE_YEAR_TTL_HRS ? createReq.getTtlInHrs()
							: DBConstants.DIPCOIN_ONE_YEAR_TTL_HRS)
					: (account.getDipcoinExpiryTTL() > 0 ? account.getDipcoinExpiryTTL()
							: DBConstants.DIPCOIN_ONE_YEAR_TTL_HRS);

		} else {
			ttl = createReq.getTtlInHrs() != null
					? (createReq.getTtlInHrs() < DBConstants.DIPCOIN_MAX_TTL_HRS ? createReq.getTtlInHrs()
							: DBConstants.DIPCOIN_MAX_TTL_HRS)
					: (account.getDipcoinExpiryTTL() > 0 ? account.getDipcoinExpiryTTL()
							: DBConstants.DIPCOIN_MAX_TTL_HRS);
		}

		LOG.debug(LogFormatter.instance(httpServletContext.getTraceId()).data("UserTTL", createReq.getTtlInHrs())
				.data("AccountTTL", account.getDipcoinExpiryTTL()).data("FinalTTL", ttl).format());

		Dipcoin dipCoin = this.coinDBService.createCoin(dcoin, ttl);
		
		if(dipCoin == null) {
	        LOG.debug(LogFormatter.instance(httpServletContext.getTraceId()).message("Dipcoin Not Generated").format());
		} else {
		  LOG.debug(LogFormatter.instance(httpServletContext.getTraceId()).message("Dipcoin  Generated").format());
		}
		
		return dipCoin;
		
	}
 
 public Dipcoin generateDipcoin(final CustomerDipcoinRequest createReq, final Dipcoin dcoin,
			final CustomerAccount account) {
		Dipcoin coin = this.coinDBService.createCoin(dcoin,
				createReq.getTtlInHrs() != null ? createReq.getTtlInHrs() : account.getDipcoinExpiryTTL());
		return coin;
	}

	public String getUniqueToken(final User user) {
		// * Get Customer osta
		List<Dipcoin> existingDipcoin = this.coinDBService.getDipcoinByUserId(user.getId());
		if(existingDipcoin != null && existingDipcoin.size() > 0) {
			String coin = existingDipcoin.get(0).getCoin();
			Integer incrementCoin = Integer.getInteger(coin) + 1;
			return String.valueOf(incrementCoin);
		}
		return CoreUtils.generateDipcoinToken();
		
	}
	
		  
		  protected void saveFailureDipcoinTransaction(final DipcoinTransaction transaction,
			      HttpStatus status, HeaderCode code) {
			    try {
			      String now = String.valueOf(DateTime.now(DateTimeZone.UTC).getMillis());
			      LOG.debug(LogFormatter.instance(httpServletContext.getTraceId())
			          .message("Adding failure dipcoin transaction").data("transaction", transaction).format());
			      transaction.setDCResponseCode(String.valueOf(status.value()));
			      transaction.setDCResponseDesc(code.message());
			      transaction.setType(DipcoinTransactionType.VALIDATION_FAILURE.value());
			      transaction.setStatus(DipcoinTransactionsStatus.FAILURE.value());
			      transaction.setResponseTime(now);
			      transaction.setUpdateDate(now);

			      saveDipcoinTransaction(transaction);
			    } catch (Exception e) {
			      LOG.error(LogFormatter.instance(httpServletContext.getTraceId())
			          .message("Failed to add dipcoin transaction").format(), e);
			    }
			  }	  
		  
		  /*
		   * 
		   */
		  protected void saveDipcoinTransaction(final DipcoinTransaction transaction) {
		    try {
		      LOG.debug(LogFormatter.instance(httpServletContext.getTraceId())
		          .message("Adding dipcoin transaction").data("transaction", transaction).format());
		      // add transaction
		      DipcoinTransaction persisted = coinDBService.asyncAddTransaction(transaction).get();
		      if (persisted == null) {
		        LOG.error(LogFormatter.instance(httpServletContext.getTraceId())
		            .message("Failed to add dipcoin transaction").data("transaction", transaction)
		            .format());
		      } else {
		        LOG.debug(LogFormatter.instance(httpServletContext.getTraceId())
		            .message("Added dipcoin transaction").data("transaction", persisted).format());
		      }
		    } catch (Exception e) {
		      LOG.error(LogFormatter.instance(httpServletContext.getTraceId())
		          .message("Failed to add dipcoin transaction").format(), e);
		    }
		  }
		  
		  
		  protected void autogenerateDipcoin(final Dipcoin parent, final CustomerAccount account,
			      BigDecimal amount, TransactionSource source) {
			    LOG.debug(LogFormatter.instance(httpServletContext.getTraceId())
			        .data("DipcoinAutoGenerate", account.getDipcoinAutoGenerate()).data("amount", amount)
			        .data("ThresholdAmount", account.getThresholdAmount()).format());
			    if ((TransactionSource.TOLL.equals(source)
			        && BigDecimal.ONE.compareTo(amount) <= NumberUtils.INTEGER_ZERO)
			        || account.getDipcoinAutoGenerate() == BooleanStatus.YES.value()
			            && amount.compareTo(account.getThresholdAmount() != null ? account.getThresholdAmount()
			                : DBConstants.DIPCOIN_THRESHOLD_MIN_AMOUNT) > 0) {

			      AutoGenerateDipcoinRequest dReq = new AutoGenerateDipcoinRequest();
			      dReq.setCardId(account.getUserCardId());
			      dReq.setTtlInHrs(TransactionSource.TOLL.equals(source) ? DBConstants.DIPCOIN_ONE_YEAR_TTL_HRS
			          : account.getDipcoinExpiryTTL());
			      if (parent.getUsageType() == DBConstants.DipcoinUsageType.WALLET.value()) {
			        dReq.setTtlInHrs(DBConstants.DIPCOIN_ONE_YEAR_TTL_HRS);
			      }
			      dReq.setAmount(amount);
			      dReq.setParentDipcoinId(parent.getId());
			      dReq.setAccountId(account.getId());
			      dReq.setUsageType(parent.getUsageType());
			      dReq.setUsageCategory(parent.getUsageCategory());

			      LOG.debug(LogFormatter.instance(httpServletContext.getTraceId())
			          .message("Init Autogenerate request").data("Parent Dipcoin", parent.getCoin())
			          .data("DipcoinRequest", dReq).format());
			      
			      
			      try {
			        internalResource.autoGenerateDipcoin(account.getUser(), dReq, httpServletContext.getTraceId());
			      } catch (Exception e) {
			        
			        LOG.debug(LogFormatter.instance(httpServletContext.getTraceId())
			            .message("Init Autogenerate Exception").format(),e);
			      }

//			      AsyncRequest<DipcoinRequest> aReq = new AsyncRequest<>();
//			      aReq.setRawRequest(dReq);
//			      aReq.setUserId(account.getUser().getId());
//			      aReq.setTraceId(httpServletContext.getTraceId());
			            
			      //asyncRequestAmqpTemplate.convertAndSend(RabbitMqConfiguration.ASYNC_REQUEST_QUEUE, aReq);
			      dipcoinMetricRegistry.dipcoinAutoCreated().increment();

			    }
			  }
		  
		  /*
		   * 
		   */
		  public static DipcoinTransaction initiateDipcoinTransaction(final Dipcoin dcoin, final User user,
		      String originIp) {
		    DipcoinTransaction transaction = new DipcoinTransaction();
		    String now = String.valueOf(DateTime.now(DateTimeZone.UTC).getMillis());
		    transaction.setAmount(dcoin.getAmount());
		    transaction.setDipcoinId(dcoin.getId());
		    transaction.setUpdateDate(now);
		    transaction.setIPAddress(originIp);
		    transaction.setUser(user);
		    if (dcoin.getCustomerAccount() != null)
		      transaction.setCustomerAccountId(dcoin.getCustomerAccount().getId());

		    return transaction;
		  }
		  
			public CustomerAccount getAccount(Integer userId, Integer cardId) {
			    return customerDBService.getAccount(userId, cardId);
			  }
}
