package com.dipcoin.api.resource;

import java.security.SecureRandom;
import java.util.List;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.joda.time.DateTime;
import org.joda.time.DateTimeZone;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.util.CollectionUtils;
import com.dipcoin.api.async.AsyncRequest;
import com.dipcoin.api.filter.HttpServletContext;
import com.dipcoin.api.model.AutoGenerateDipcoinRequest;
import com.dipcoin.api.model.DipcoinRequest;
import com.dipcoin.bank.services.client.BankClient.Operation;
import com.dipcoin.bank.services.utils.BankUtils;
import com.dipcoin.commons.Constants;
import com.dipcoin.commons.CoreUtils;
import com.dipcoin.commons.LogFormatter;
import com.dipcoin.db.services.BankDBService;
import com.dipcoin.db.services.CustomerDBService;
import com.dipcoin.db.services.DipcoinDBService;
import com.dipcoin.db.services.UserDBService;
import com.dipcoin.db.services.commons.DBConstants.BankTransactionType;
import com.dipcoin.db.services.commons.DBConstants.CustomerAccountStatus;
import com.dipcoin.db.services.commons.DBConstants.DipcoinTransactionType;
import com.dipcoin.db.services.commons.DBConstants.DipcoinTransactionsStatus;
import com.dipcoin.db.services.dao.DipcoinDao;
import com.dipcoin.db.services.model.CustomerAccount;
import com.dipcoin.db.services.model.Dipcoin;
import com.dipcoin.db.services.model.DipcoinTransaction;
import com.dipcoin.db.services.model.User;
import com.fasterxml.jackson.databind.ObjectMapper;

/**
 *
 */
@Component("internalResource")
@Transactional(rollbackFor = {Exception.class}, propagation = Propagation.REQUIRES_NEW)
public class InternalResource {

  private static final Logger LOG = LogManager.getLogger(InternalResource.class);
  private final static SecureRandom randomGenerator = new SecureRandom();

  @Autowired
  private UserDBService userDBService;

  @Autowired
  private CustomerDBService customerDBService;

  @Autowired
  private DipcoinDao dipcoinDao;

  @Autowired
  private DipcoinDBService coinDBService;

  @Autowired
  private BankDBService bankDBService;

  @Autowired
  private BankUtils bankUtils;

//  @Autowired
//  private APIFeatureFlags apiFeatureFlags;
  
  @Autowired
  private DipcoinResource dipcoinResource;
  
//  @Autowired
//  private BankAPIServices bankAPIServices;

  /*
   * @Autowired
   * 
   * @Lazy
   */
  // private HttpServletContext httpServletContext;

  private static final ObjectMapper objectMapper = new ObjectMapper();

  /**
   * @param httpServletContext2
   * 
   */
  public void autoGenerateDipcoin(final User user, final AutoGenerateDipcoinRequest createReq,
      final String traceId) throws Exception {

    HttpServletContext httpServletContext = HttpServletContext.instance();
    httpServletContext.setTraceId(traceId);

    AsyncRequest<DipcoinRequest> aReq = new AsyncRequest<>();
    // this.httpServletContext = objectMapper.readValue(httpServletContext,
    // HttpServletContext.class);

    String requestTime = String.valueOf(DateTime.now(DateTimeZone.UTC).getMillis());
    String clientTransactionId = String.valueOf(Math.abs(randomGenerator.nextLong()));


    LOG.debug(
        LogFormatter.instance(httpServletContext.getTraceId()).data("DipcoinRequest", createReq)
            .data("clientTransactionId", clientTransactionId).format());



    // validate request
    if (createReq == null || !createReq.validate(httpServletContext)) {
      LOG.error(LogFormatter.instance(httpServletContext.getTraceId()).message("Invalid Request")
          .format());
      return;
    }

    if (!this.userDBService.isCustomer(user)) {
      LOG.error(LogFormatter.instance(httpServletContext.getTraceId())
          .message("User not customer: " + user.getId()).format());
      return;
    }

    // get customer account, fetch bank and verify bank

    LOG.debug(
        LogFormatter.instance(httpServletContext.getTraceId()).message("Fetch CustomerAccount")
            .data("UserId", user.getId()).data("CardId", createReq.getCardId()).format());

    Dipcoin parentCoin = dipcoinDao.find(createReq.getParentDipcoinId());
    if (parentCoin == null) {
      LOG.error(LogFormatter.instance(httpServletContext.getTraceId())
          .message("Invalid parent dipcoin: " + createReq.getParentDipcoinId()).format());
      return;
    }

    // check if parent already has children or not expired
    List<Dipcoin> children = dipcoinDao.findChildrenDipcoins(parentCoin.getId());
    if (!CollectionUtils.isEmpty(children)) {
      LOG.error(LogFormatter.instance(httpServletContext.getTraceId())
          .message("Parent already processed: " + parentCoin.getId()).format());
      return;
    }
    if (new DateTime(Long.parseLong(parentCoin.getExpiryTime())).isBeforeNow()) {
      LOG.error(LogFormatter.instance(httpServletContext.getTraceId())
          .message("Expired parent dipcoin " + parentCoin.getId()).format());
      return;
    }

    // fetch customer account
    CustomerAccount account =
        this.customerDBService.getAccount(user.getId(), createReq.getCardId());

    // account exists
    if (account == null || !CustomerAccountStatus.ACTIVE.equals(account.getStatus())) {
      LOG.error(LogFormatter.instance(httpServletContext.getTraceId())
          .message("Invalid/Inactive account. Status: " + account.getStatus()).format());
      return;
    }

    // if account bank active
    if (!bankDBService.isActive(account.getBank())) {
      LOG.error(LogFormatter.instance(httpServletContext.getTraceId())
          .message(
              "Bank not active " + (account.getBank() != null ? account.getBank().getId() : ""))
          .format());
      return;
    }

    // validate if sufficient funds available
    if ((account.getMaxCoinLimit() != null && createReq.getAmount() != null
        && account.getMaxCoinLimit().compareTo(createReq.getAmount()) < 0)
        || parentCoin.getAmount().compareTo(createReq.getAmount()) < 0) {
      LOG.error(LogFormatter.instance(httpServletContext.getTraceId()).message("Insufficient funds")
          .data("MaxCoinLimit", account.getMaxCoinLimit())
          .data("Request Amount", createReq.getAmount())
          .data("Parent Amount", parentCoin.getAmount()).format());
      return;
    }

    // generate token + additional metadata
    //String token = CoreUtils.generateDipcoinToken();

		/*
		 * LOG.debug(LogFormatter.instance(httpServletContext.getTraceId()).data(
		 * "Phone", user.getPhone()) .data("Coin", token).format());
		 */

    // create dipcoin in DB
    Dipcoin dcoin = new Dipcoin();
    dcoin.setUser(user);
    dcoin.setAmount(createReq.getAmount());
    dcoin.setCustomerAccount(account);
    dcoin.setClientTransactionId(clientTransactionId);
    dcoin.setParentDipcoinId(createReq.getParentDipcoinId());
    dcoin.setUsageType(createReq.getUsageType());
    dcoin.setUsageCategory(createReq.getUsageCategory());
    
    boolean isduplicate = false;
    for (int i = 0; i <= 3; i++) {
		try {
			String token = CoreUtils.generateDipcoinToken();
			LOG.debug(LogFormatter.instance(httpServletContext.getTraceId()).data("Phone", user.getPhone())
			        .data("Coin", token).format());
			dcoin.setCoin(token);
			dcoin = dipcoinResource.generateDipcoin(createReq, dcoin, account);
			isduplicate = false;
			break;
		} catch (Exception e) {
			if (e.getCause() != null && e.getCause().getCause() != null && e.getCause().getCause().getMessage().contains("Duplicate")) {
				LOG.debug(LogFormatter.instance(httpServletContext.getTraceId()).message("Duplicate Coin Exception occoured").format());
				isduplicate = true;
				continue;
			}
			break;
		}
	}
    
    if(isduplicate) {
    	dcoin.setCoin(dipcoinResource.getUniqueToken(user));
		dcoin = dipcoinResource.generateDipcoin(createReq, dcoin, account);
	}	

    // dipcoin created
    if (dcoin != null) {
      // add generate transaction
      DipcoinTransaction dTx =
          DipcoinResource.initiateDipcoinTransaction(dcoin, user, Constants.ZERO_IP);
      dTx.setType(DipcoinTransactionType.GENERATE_DIPCOIN.value());
      String dipcoinReferenceNumber =
          bankUtils.generateDipcoinToBankReferenceNumber(account.getBank().getReferenceId(),
              Operation.MARK_LIEN, BankTransactionType.LIEN_MARK.value());
      dTx.setDipcoinTransactionRefId(dipcoinReferenceNumber); // @NOTE
                                                              // Dummy
                                                              // RefNumber
      dTx.setStatus(DipcoinTransactionsStatus.SUCCESS.value());
      dTx.setRequestTime(requestTime);
      dTx.setDipcoinId(dcoin.getId());
      dTx.setResponseTime(String.valueOf(DateTime.now(DateTimeZone.UTC).getMillis()));
      if ((dTx = this.coinDBService.addTransaction(dTx)) == null) {
        LOG.error(LogFormatter.instance(httpServletContext.getTraceId())
            .message("Failed to add Dipcoin Transaction").data("transaction", dTx).format());
      }


      LOG.debug(LogFormatter.instance(httpServletContext.getTraceId()).message("Create dipcoin")
          .data("Coin", dcoin.getCoin()).data("Amount", dcoin.getAmount())
          .data("ExpiryTime", dcoin.getExpiryTime()).format());

    } else {
      LOG.error(LogFormatter.instance(httpServletContext.getTraceId())
          .message("Failed to create child dipcoin").data("parent", createReq.getParentDipcoinId())
          .format());
    }        
  }
  

}
