package com.dipcoin.api.resource;

import com.dipcoin.api.model.AutoGenerateDipcoinRequest;
import com.dipcoin.db.services.model.User;

public class InternalResource {

	public void autoGenerateDipcoin(User user, AutoGenerateDipcoinRequest dReq, String traceId) {
		// TODO Auto-generated method stub
		
	}

}
