package com.dipcoin.api.commons;

import java.util.HashSet;
import java.util.Set;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/*
 * Declare all relevant message here.
 * 
 * @TODO - Clean up message language
 */
public enum HeaderCode {
  // @TDOD - Refactor language and standardize naming convention
  // customer error code range C-<001-009> - customer code

  //@formatter:off
  USER_NOT_ACTIVE("C-001", "User is not activated."), 
  USER_EXISTS("C-002", "User already exists."), 
  USER_VERIFY_EMAIL_FAILURE("C-003", "Failed to send verification email."), 
  USER_VERIFY_SMS_FAILURE("C-004", "Failed to send OTP SMS."), 
  USER_REGISTERED("C-005", "User is registered."), 
  USER_DOESNT_EXIST("C-006", "User doesn't exist."), 
  USER_INVALID_PASSWORD("C-007", "Invalid password."), 
  USER_UPDATED("C-008", "User updated."), 
  USER_UNAUTHORIZED("C-009", "User is not authorized to use this service."), 
  USER_AUTHORIZED("C-010", "Authorized user"), 
  USER_ACTIVE("C-011", "User active"), 
  USER_INVALID_EMAIL("C-012",  "Invalid email"), 
  USER_INVALID_PHONENUM("C-013", "Invalid mobile number"),
  USER_RESET_EMAIL_SMS_SEND("C-014", "Reset email/sms send,"),
  USER_ACTIVATED("C-015", "User has been activated."), 
  USER_EMAIL_VERIFIED("C-016", "User email has been verified."), 
  USER_MOBILE_VERIFIED("C-017", "User mobile has been verified."), 
  USER_PASSWORD_RESET("C-018", "Password has been reset."), 
  USER_VERIFICATION_REJECT("C-019", "Request rejected by user."), 
  USER_EMAIL_NOT_VERIFIED("C-020", "User email has not been verified."), 
  USER_MOBILE_NOT_VERIFIED("C-021", "User mobile has not been verified."), 
  USER_INVALID_SECRET_QUEANS("C-022", "Invalid secret question/answer"), 
  USER_OTP_EXPIRED("C-023", "OTP entered has Expired! Please try resend OTP."), 
  USER_TNC_NOT_VERIFIED("C-024", "TnC not verified"), 
  USER_OLD_PASSWORD_MISSING("C-025", "Old Password is missing."), 
  USER_INVALID_PIN("C-026", "Invalid pin provided."), 
  USER_INVALID_TNC("C-027", "TnC has not been accepted."),
  USER_ACCOUNT_ADDED("C-028", "New account added successfully."),
  USER_ACCOUNT_DOESNT_EXIST("C-029", "Requested account doesn't exist."),
  USER_ACCOUNT_EXIST("C-030", "Account already exists, please try again with other credentials."),
  USER_ACCOUNT_ACTIVATED("C-031", "Account has been activated."),
  USER_ACCOUNT_UPDATED("C-032", "User account has been updated."),
  USER_ACCOUNT_INACTIVE("C-033", "Account is inactive."),   
  USER_DEACTIVATED("C-034", "User details has been deleted successfully."),
  DIPCOIN_ACTIVE("C-035", "Active Osta"),
  DIPCOIN_INVALID("C-036", "Invalid Osta details provided."),
  DIPCOIN_DOESNT_EXIST("C-037", "Osta doesn't exist."),
  DIPCOIN_EXPIRED("C-038", "Expired Osta."),
  DIPCOIN_DELETED("C-039", "Osta has been deleted successfully."),
  DIPCOIN_INSUFFICIENT_FUNDS("C-040", "Osta value less than transaction amount"),
  DIPCOIN_NOT_ACTIVE("C-041", "Osta is not active and cannot be processed."),
  DIPCOIN_PROCESS_SUCCESS("C-042", "Osta processed successfully"),
  DIPCOIN_NOT_SETTLED("C-043", "Osta Transaction is not settled."),
  DIPCOIN_PROCESSING_PENDING("C-044", "Osta process is pending."),
  DIPCOIN_INVALID_USAGE_TYPE("C-045", "Invalid Osta usage type."),
  DIPCOIN_INVALID_TX_REF("C-046", "Invalid Osta transaction reference"),
  DIPCOIN_MAX_PER_TRANSACTION_LIMIT("C-047", "Transaction amount greater than per transaction limit."),
  MAX_OTP_RESEND_ATTEMPT("C-048", "OTP resend limit exceeded. Please contact Osta team"),
  BRONTOO_INVALID_ROLE("C-049", "Invalid role."),
  INVALID_REQUEST("C-050", "Invalid user request."),
  PARTNER_REF_ID_NOT_PROVIDED("C-051", "Partner ReferenceId is missing."),
  FAIL_TO_ADD_USER("C-052", "User addition has failed."),
  USER_NOT_UPDATED("C-053", "User updation failed."),
  FAILED_TO_UPDATE_TNC("C-054", "TnC not accepted."),
  FAILED_TO_UPDATE_USER("C-055", "User updation failed."),
  TNC_NOT_PROVIDED("C-056", "User updation failed."),
  FAIL_TO_VALIDATE_EMAIL_PHONE("C-057", "Invalid email/mobile number."),
  USER_FAIL_TO_VERIFY("C-058", "User verification failed."),
  MAX_OTP_VERIFICATION_ATTEMPT("C-059", "You have exceeded maximum attempts. Please retry after 30 mins."),
  DIPCOIN_EQUAL_TO_ZERO("C-060", "Osta amount is zero."),
  MISSING_USER_PASSWORD("C-061", "Missing user password."),
  MISSING_INVALID_LOGIN_ID("C-062", "Missing/Invalid user login id."),
  USER_INVALID_OTP("C-063", "OTP entered is not correct."),
  INVALID_ORDERID("C-064", "Invalid orderId"),
  FAILED_TO_VALIDATE_TOKEN("C-065", "Duplicate login attempt."),
  INVALID_ACCOUNT_NUMBER("C-066", "Invalid account number."),
  INVALID_USER_ACCOUNT_TYPE("C-067", "Invalid account method type."),
  INVALID_ACCOUNT_NUMBER_SIZE("C-068", "Invalid account number size."),
  OSTA_THRESHOLD_BREACHED("C-069", "Osta threshold has been breached."),
  OSTA_EXPIRED_TIME("C-070", "Osta has expired."),
  INVALID_CARD_ID("C-071", "Invalid account details provided."),
  INVALID_USAGE_CATEGORY("C-072", "Invalid usage details provided."),
  INVALID_AUTHORIZATION_PIN("C-073", "Invalid authorization or Osta pin entered."),
  INVALID_EMAIL_OR_PHONENUM("C-074", "Invalid email/mobile number."),
  INVALID_USER_AGENT("C-075", "Invalid user agent"),
  INVALID_IMEI_NO("C-076", "Invalid IMEI no"),
  USER_INVALID_FNAME("C-077", "Invalid first name"),
  USER_INVALID_LNAME("C-078", "Invalid last name"),
  INVALID_USER_LOGIN("C-079", "Invalid user login"),
  INVALID_USER_CREDENTIAL("C-080", "Invalid user credential"),
  INVALID_BANK_REF_ID("C-081", "Invalid bank ReferenceId"),
  INVALID_USER_KYC_NUMBER("C-082", "KYC id invalid"),
  ACCOUNT_HOLDER_NAME_NOT_CORRECT("C-083", "Invalid user account holder name"),
  ACCOUNT_NUMBER_NOT_CORRECT("C-084", "Invalid account number"),
  IFSC_CODE_NOT_CORRECT("C-085", "Invalid IFSC code"),
  USER_PER_TRANSACTION_LIMIT("C-086", "Transaction limit breached"),
  USER_PER_DAY_LIMIT("C-087", "Per day transaction limit breached"),
  USER_PER_MONTH_LIMIT("C-088", "Per month transaction limit breached"),
  USER_PER_YEAR_LIMIT("C-089", "Per year transaction limit breached"),
  USER_DEVICE_INVALID_TOKEN("C-090", "Invalid device token provided"),
  EMAIL_SENT_SUCCESSFULLY("C-091", "Email sent successfully"),
  CUSTOMER_ACCOUNT_ACTIVE("C-092", "Bank Account is Active"),
  USER_ON_HOLD("C-093", "Maximum login attempts exceeded. Try Forgot Password after 30 minutes"),
  HOLD_OFFSET_NOT_COMPLETED("C-094","User has been blocked. Please try again after some time"),
  INCORRECT_OTP("C-095","Incorrect OTP."),
  INVALID_AUTHORIZATION_METHOD("C-096", "Invalid authorization method"),
  INVALID_USER("C-097", "User of this type doesn't exist."),
  INVALID_SESSION("C-098", "User not logged in."),
  
  
 

  INVALID_CONSUMER_NUMBER("C-099","Consumer number provided is not correct"),
  INVALID_CIRCLE("C-100","Circle selected is not correct."),
  INVALID_SP_CODE("C-101","Operator selected is not correct."),
  FAIL_TO_RECHARGE("C-102", "Failed to Recharge, system shall validate and auto-refund transaction if amount is deducted, in 24-48 hours."),
  FAIL_TO_FETCH_TRANSACTION("C-103", "Please try again, we are unable to fetch your transaction."),
  FAIL_TO_VALIDATE_RECHARGE_BILL("C-104", "Information provided could not be validated with Biller, please check and try again later."),
  RECHARGE_SUCCESS("C-105","Thanks for using Osta.Your recharge has been successful."),
  INVALID_MISSING_RECHARGE_BILL_INFORMATION("C-106", "Please enter correct details and try again."),
  FAIL_TO_PAY_BILL("C-107", "Your bill payment has failed. System shall validate it again and initiate auto-refund, if applicable in 24-48 hours."),
  FAIL_TO_FETCH_BILL("C-108", "Please try again, your bill could not be fetched"),
  BILL_PAYMENT_SUCCESS("C-109", "Thanks for using Osta.Your bill payment has been successful."),
  FAILED_TRANSACTION("C-110","Your transaction has failed, system shall validate the transaction and auto-refund if amount has been deducted in 24-48 hours."),
  SUCCES_TRANSACTION("C-111","Your transaction has been successful."),
  BILLER_NOT_FOUND("C-112","No such biller is available at the moment.Please try later."),
  BILL_PAYMENT_RECHARGE_PENDING("C-113","Your transaction is pending. System shall check status in 4 hours. Auto-refund shall be initiated in 24-48 hours, if transaction status is failed and amount is deducted."),
  MISSING_BILLER_ID("C-161","Biller Id is missing, please enter the valid Biller Id"),
  
//OSTAA APP UPDATES
  USER_APP_ALREADY_UPDATED("C-114", "User App already updated"),
  UPDATE_AVAILABLE("C-115", "New version is available, please update."),
  UPDATE_AVAILABLE_AND_MANDATORY("C-116", "New version is available and is mandatory, please update."),
  TRANSACTION_DOESNT_EXIST("C-117", "Transaction doesn't exist."),
  USER_INVALID_ROLE("C-118","Role Invalid"),
	  
  //chargeBack
  CHARGE_BACK_INELIGIBLE("C-119", "Dispute cannot be initiated, time limit exceeded."),
  FAILED_TO_ADD_CHARGE_BACK_TRANSACTION("C-120", "Failed to initiate dispute transaction. Please try later."),
  CHARGE_BACK_ALREADY_INITIATED("C-121", "Dispute is under process."),
  CHARGEBACK_REQUEST_ACCEPTED("C-122","Dispute request accepted."),
  DATA_UPDATED("C-123","Data updated"),
  USER_ACCOUNT_DELETED("C-124","Please delete any active Osta and try after 24 hours. Account can be only deleted if there are no settlements pending and no active Osta."),
  ACCOUNT_OTP_SENT("C-125","OTP sent to registered mobile number."),
  USER_ACCOUNT_ALREADY_DELETED_DEACTIVATED("C-126","The bank account you are trying to deactivate is already deleted or deactivated."),
  USER_BANK_ACCOUNT_DEACTIVATED("C-127","The bank account of the customer is deactivated successfully."),
  MISSING_INVALID_USER_CHANNEL("C-128","Access forbidden for this user channel as it is an invalid channel or no such channel is present."),
  MOBILE_NOT_REGISTERED("C-129","Mobile number invalid/not registered in bank."),
  MISSING_VERSION("C-130","Missing App Version."),
  COMPLIANCE_INELIGIBLE("C-131", "Cannot initiate compliance, max compliance time limit exceeded."),
  AMOUNT_IS_GREATER("C-132", "Amount is Greater than transaction amount."),
  INVALID_USER_STATUS("C-133","Invalid User Status."),
  AMOUNT_LESS_THAN_MDM_STANDARD("C-134", "Please add an amount greater or equal to 50."),
  INCORRECT_TPIN("C-135", "Please try with valid TPIN."), 
  USER_DELETED_REREGISTER_AGAIN("C-136", "User is deleted from the system for security reasons , Please re-register yourself again."),
  RETRY_AFTER_OSTAS_ARE_SETTLED("C-137", "Failed to delete Bank Account of user due to Osta used or debit pending, Please try Forgot Pin after 24-48 hours, Till then don't do any transactions from your account."),
  PAYMENT_CHANNEL_MODE_NOT_SUPPORTED_BILLER("C-138", "Biller does not support the present payment method selected. Hence bill could not be paid."),
  MISSING_PAYMENT_MODE("C-139", "Missing or Invalid PaymentMode"),
  MISSING_CHANNEL_CODE("C-140", "Missing or Invalid ChannelCode"),
  BILL_PAYMENT_STATUS_CHECK("C-141", "Please check your transaction status after 24-48 hours."),
  FAILED_TO_UPDATE_BANKUID("C-142", "Could not validate and link your account. If problem persist, please write to us."),
  EMAIL_CANNOT_SEND("C-143", "Failed to send Email"),
  UPDATE_TPIN_FOR_BANK_APP_USER_FIRST("C-144", "Please login into your Bank App and Update TPIN and login from App first. After that try forgot password here."),
  USER_ACCOUNT_ALREADY_LINKED ("C-145", "Account already linked using another method."),
  USER_BANK_TRANSACTION_FAILED("C-146","Your recharge or bill payment is incomplete as your bank transaction has failed. If you opted for fund transfer, refund will be transfered to your account number within 48hrs."),
  USER_REQUEST_STATUS_TRANSACTION_PENDING("C-147","We are unable to fetch status of your transaction from the biller or operator at the present moment.Please try later."),
  INVALID_EMAIL_DOMAIN("C-148","The Email domain is invalid."),
  CUSTOMER_ACCOUNT_CANNOT_BE_DELETED ("C-149", "Account cannot be deleted as Tags are Active"),
  CUSTOMER_ACCOUNT_NOT_UPDATED("C-150","Unable to update Customer Account."),
  CUSTOMER_ACCOUNT_UPDATED("C-151","Customer Account updated."),
  FAILED_FETCHING_CUSTOMER_ACCOUNT("C-152","Failed to fetch Customer Account."),
  MISSING_USER_CARDID("C-153","Missing User CardId."),
  CUSTOMER_ACCOUNT_DOESNT_EXIST("C-154", "No such customer account"),
  CUSTOMER_ACCOUNT_DOESNT_EXIST_OR_CUSTOMER_NOT_LINKED_TO_THE_BANK("C-155", "No CustomerAccounts of the User linked with the Bank or Account doesnt exists."),
  CHARGE_BACK_CANNOT_BE_INITIATE("C-156", "Dispute can be initiate after 24 hours."),
  MAXIMUM_ATTEMPT_REACHED_COIN_GENERATION("C-157", "maximum attempt reached for coin genration because of duplicate coin number"),
  AMOUNT_LESS_THAN_TATA_PLAY_STANDARD("C-158", "Please add an amount greater or equal to 100."),  // DTH Tata Play requirement min amt shld be 100
  FAILED_TO_REFUND("C-159", "Failed to Refund Amount"), 
  BANK_ACCOUNT_NOT_OF_BBPS_BANKS("C-159","Can't use selected bank Account for BBPS or Recharge"), // we'll use this when customer use CBI bank acc for BBPS
  NEW_PASSWORD_SAME_AS_OLD_PASSWORD("C-160","New Password cannot be same as the Old Password"),
  NEW_PIN_SAME_AS_OLD_PIN("C-160","New Pin cannot be same as the Old Pin"),
  MISSING_CUSTOMER_ACCOUNT("C-161","Missing Customer Account No"),
  PHONE_NUMBER_ALREADY_REGISTERED("C-162", "Phone number already registered, please try again with another phone number"),
   //Merchant error code range M-<001-009> - merchant code

  MERCHANT_NOT_ACTIVE("M-001", "Merchant not active"),
  MERCHANT_USER_NOT_ACTIVE("M-002", "Merchant not active"),
  MERCHANT_DOESNT_EXIST("M-003", "No such merchant"),
  MERCHANT_UPDATED("M-004", "Merchant updated"),
  MERCHANT_ACTIVATED("M-005", "Merchant activated"),
  MERCHANT_INVALID_ROLE("M-006", "Invalid merchant role"),
  MERCHANT_EXISTS("M-007", "Merchant already exists"),
  MERCHANT_UNAUTHORIZED("M-008", "Unauthorized merchant"),
  MERCHANT_TX_REF_NOT_PROVIDED("M-009", "Reference not provided "),
  MERCHANT_MISSING_ORDERID("M-010", "Order id missing"),
  MERCHANT_TX_CANCEL_INELIGIBLE("M-011", "Transaction cannot be cancelled"),
  MERCHANT_USER_NOT_ADMIN("M-012", "User not admin"),
  MERCHANT_USER_NOT_SUPERADMIN("M-013", "User not superadmin"),
  TX_ALREADY_CANCELED("M-014", "Transaction already cancelled"),
  INVALID_MERCHANT_TX_REFID("M-015", "Invalid transaction Id "),
  MERCHANT_MISSING_CURRENCY("M-016", "Invalid currency"),
  MERCHANT_MISSING_AMOUNT("M-017", "Invalid amount"),
  MERCHANT_MISSING_OSTA("M-018", "Osta unavailable"),
  INVALID_MERCHANT_STATUS("M-019", "Missing/Invalid status"),
  MERCHANT_DETAILS_VALIDATE("M-020", "Please add valid details for submission."),
  FAILED_TO_ADD_CHARGES_DETAILS("M-021", "The merchant charge details are null."),
  MERCHANT_AND_ITS_USERS_DEACTIVATED("M-022", "Merchant and its respective users are deleted successfully"),
  MISSING_EMAIL_ID("M-023", "Missing Email Id."),
  FAILED_TO_ADD_PARTNER_DETAILS("M-024", "Partner Details are not added successfully."),
  FAILED_TO_ADD_PARTNER_ACCOUNT_DETAILS("M-025", "Partner Account Details are not added successfully."),
  MERCHANT_TX_CANCEL_INELIGIBLE_INSUFFICIENT_FUND("M-026", "Insufficient amount in your today’s settlement. Please try later."),
  FAILED_TO_ADD_PARTNER_CHARGES_DETAILS("M-027", "Failed to add data of Partner Charges."),
  MISSING_PARTNER_CHARGE_PARAMETERS("M-028", "Missing Partner Charge Parameters."),
  PARTNER_DOESNT_EXIST("M-029", "No such Partner"),
  MISSING_PAYMENT_GATEWAY_REFERENCE_ID("M-030", "Payment Gateway ReferenceId is missing"),
  PAYMENT_GATEWAY_DOESNT_EXIST("M-031", "No such Payment Gateway"),
  FAILED_TO_ADD_PAYMENT_GATEWAY_OPTION_DETAILS("M-032", "Failed to add data of Payment Gateway Option."),
  FAILED_TO_ADD_PARTNER_PG_CHARGES_DETAILS("M-033", "Failed to add data of Partner Pg Charges."),
  MISSING_PAYMENT_GATEWAY_OPTION_TYPE("M-034", "Payment Gateway Option type is missing."),
  TOLL_MERCHANT_DOESNT_EXIST("M-035", "Toll Merchant Does Not Exist"),
  MERCHANT_DOCUMENT_DOESNT_EXIST("M-036", "Missing Merchant Document"),
  MISSING_DOCUMENT_DATA("M-037", "Missing Document related data"),
  FAILED_DELETION_OF_MERCHANT_DOC_FROM_S3_BUCKET("M-038", "Failed to delete Merchant Document from Aws S3 Bucket."),
  MISSING_SELECTION_OF_CERTAIN_PARAMETERS("M-039", "Missing selection of certain parameters in the form will not allow to verify and activate the Merchant, Please go back and select all the parameters required."),
  INVALID_INTEGRATION_TYPE("M-040", "Invalid Integration Type of Merchant or Bank, so the credentails cannot be added."),
  PARTNER_CREDENTIALS_EXISTS("M-041", "Credentials exists for particular Bank or Merchant, You may update the credentials"),
  FAILED_TO_ADD_OR_UPDATE_CREDENTIALS("M-043", "Failed to add / update Partner Credentials details."),
  TAG_MERCHANT_DOESNT_EXIST("M-044", "Tag Merchant does not exists"),
	  

  //Bank error code range B-<001-009> - bank code
  BANK_INVALID("B-001", "Invalid bank"),
  BANK_NOT_ACTIVE("B-002", "Bank not active"),
  BANK_INVALID_ACCT("B-003", "Invalid bank account"),
  BANK_DOESNT_EXISTS("B-004", "Bank doesn't exist"),
  BANK_UNAUTHORIZED("B-005", "Unauthorized bank"),
  BANK_INVALID_ROLE("B-006", "Invalid bank role"),
  BANK_FAILED_TO_MARK_LIEN("B-007", "Lien marking failed"),
  BANK_FAILED_TO_REMOVE_LIEN("B-008", "Lien removal failed"),
  BANK_FAILED_TO_AUTHORIZE_USER("B-009", "User authorization failed"),
  BANK_FAILED_TO_VERIFY_ACCOUNT("B-010", "User verification failed"),
  BANK_FAILED_TO_RESEND_OTP("B-011", "Resend OTP failed"),
  BANK_UPDATED("B-012", "Bank updated"),
  BANK_ACTIVATED("B-013", "Bank activated"),
  BANK_EXISTS("B-014", "Bank already exists"),
  BANK_INVALID_SERVER("B-015", "Invalid bank server"),

  BANK_ACCOUNT_ADDED("B-016", "Bank account added"),
  BANK_ACCOUNT_UPDATED("B-017", "Bank account updated"),
  BANK_ACCOUNT_DELETED("B-018", "Bank account deleted"),
  BANK_ACCOUNT_EXISTS("B-019", "Bank account exists"),
  BANK_ACCOUNT_DOESNT_EXISTS("B-020", "Invalid bank account"),  
  

  PARTNER_TX_REF_NOT_PROVIDED("B-021", "Transaction ReferenceId missing"),
  PARTNER_MISSING_ORDERID("B-022", "Partner orderId missing"),
  PARTNER_INVALID_TX_REF("B-023", "Invalid or duplicate transaction reference Id"),
  BANK_USER_NOT_ADMIN("B-024", "User not admin"),
  BANK_USER_NOT_SUPERADMIN("B-025", "User not superadmin"),
  BANK_DEACTIVATED("B-026", "Bank deactivated successfully"),
  MISSING_ACCOUNT_HOLDER_NAME("B-027", "Missing account holder name"),
  MISSING_ACCOUNT_NUMBER("B-028", "Missing account number"),
  MISSING_IFSC_CODE("B-029", "Missing IFSC code"),
  MISSING_ACCOUNT_TYPE("B-030", "Missing/Invalid account type"),
  MISSING_SECRET_KEY("B-031", "Missing secret key"),
  MISSING_HOST_NAME("B-032", "Missing host name"),
  MISSING_PORT("B-033", "Missing port number"),
  MISSING_PROTOCOL("B-034", "Invalid protocol"),
  INVALID_ACCOUNT_STATUS("B-035", "Missing/Invalid status"),
  INVALID_ACCOUNT_TYPE("B-036", "Missing/Invalid account type"),
  INVALID_BANK_STATUS("B-037", "Missing/Invalid status"),
  MISSING_IS_PRIMARY_FIELD("B-038", "Missing primary field"),
  BANK_INTERNAL_USER_NOT_EXIST("B-039", "Bank internal user not found"),
  MISSING_INVALID_AUTHENTICATION_METHOD("B-040", "Missing/Invalid authentication method"),
  EMPTY_BANK_PIN("B-041", "Empty bank pin"),
  BANK_CHARGES_NOT_AVAILABLE("B-042", "Bank Charges Not Available"),
  BANK_DUPLICATE_AUTHENTICATION_METHOD("B-043", "Duplicate Authetication Method"),
  BANK_AND_ITS_USERS_DEACTIVATED("B-044", "Bank and its respective users are deleted successfully"),
  BANK_VERIFIED_SUCCESSFULLY("B-045", "Bank is verified successfully"),
  UNABLE_TO_ADD_BANK_ACCOUNT("B-046", "Bank Account is not added"),
  INVALID_BANK_TYPE("B-047", "Missing/Invalid bank type"),
  BANK_TYPE_AND_CODE_ALREADY_EXIST("B-048", "Bank Type And code Already Exist"),
  INSUFFICIENT_AMOUNT("B-049", "Insufficient account balance"),
  MISSING_BBPS_BANKACCOUNT("B-50", "Please add the your bill payments account to complete your bank approval."),
  BANK_DOCUMENT_DOESNT_EXIST("B-51", "Missing Bank Document"),
  FAILED_DELETION_OF_BANK_DOC_FROM_S3_BUCKET("B-52", "Failed to delete Bank Document from Aws S3 Bucket."),
  BANK_ACCOUNT_FUND_TRANSFER("B-53", "Account fund Transfer Successful"),
  BANK_CONFIG_DOESNT_EXIST("B-54", "Missing Bank Configuration/XML file"),
  BANK_ACCOUNT_FUND_TRANSFER_FAILED("B-55", "Account fund Transfer failed"),
  FAILED_TO_DELETE_BANK_ACCOUNT("B-56", "Bank Account deletion failed"),
  FAILED_TO_ADD_BANK_ACCOUNT("B-57", "Bank Account addition failed"),
  MISSING_FUND_TRANSFER_TRANSACTION("B-58", "Missing fund transfer transanction"),
  BANK_FUND_TRANSFER_REFUND_FAILURE("B-59", "Refund for account fund transfer transaction failed"),
  BANK_FUND_TRANSFER_REFUND_SUCCESS("B-60", "Refund for account fund transfer transaction successful"),
  BANK_AGENT_ADDED("B-61", "Bank Agent added successfully"),
  STATUS_CHECK_FAILED("B-62", "Failed to fetch status transaction from bank"),
  EMAIL_OTP_SENT("B-63","OTP sent to provided email ."),
  BANK_ACCOUNT_HOLD_NOT_PERMITTED("B-064","It seems hold transaction is not permitted on the requested account. Please retry if account is current and savings account."),
  EMAIL_OTP_SENT_FAILED("B-65","Email could not be sent, please retry after 30 minutes."),
  MISSING_BANK_REFERENCE("B-66", "Missing bank reference"),
  MISSING_BANK_ALIAS("B-67", "Missing bank alias"),
  BANK_REVERIFICATION_NOT_ALLOWED("B-68", "Please select another account for verification"),
  BANK_HOLD_MARK_FOR_HOLD_DOES_NOT_EXIT("B-069", "Hold has been marked for hold does not exist"),
  BANK_FAILED_HOLD_DOES_NOT_EXIT("B-070", "Hold does not exist"),
  BANK_SERVER_DOWN("B-071", "Bank server down try later"),
  BANK_TELLER_NOT_ACTIVE("B-072", "Bank Teller user not activated"),
  ACCOUNT_VERIFICATION_SUCCESS("B-073", "Enter OTP sent to linked mobile number"),
  ACCOUNT_VERIFICATION_FAILED("B-074", "Failed to send OTP to linked mobile number"),
  ACCOUNT_OTP_VERIFICATION_SUCCESS("B-075", "Account verified successfully"),
  ACCOUNT_OTP_VERIFICATION_FAILED("B-076", "OTP entered is incorrect"),
  INVALID_BRANCH_CODE("B-077","BranchCode not found in BankBranchDetails"),
  INVALID_REGION("B-078","Invalid Region Code"),
  INVALID_ZONE("B-079","Invalid Zone Code"),
  BALANCE_FETCH_FAILED("B-080","Failed to fetch balance"),
  ACCOUNT_NOT_PRESENT("B-081","Bank Account not present"),
  DOCUMENTS_PENDING_FROM_BANK("B-082","Documents pending from the bank"),
  DOCUMENTS_VERIFIED("B-083", "Documents verified successfully"),
  DOCUMENTS_REJECTED("B-084","Documents rejected"),
  LIEN_MARK_SUCCESS("B-085","Lien mark Success"),
  REFUND_ALREADY_DONE("B-086","Refund already processed for this dipcoinId"),
  FUND_TRANSFER_SUCCESSFUL("B-087","Fund Transfer Successful"),
  REFUND_OR_CREDIT_ALREADY_DONE("B-088","Refund Or Credit Already Done"),

  
  // Admin error code range S-<001-009> - system code
  MISSING_INVALID_INFO("S-001", "Missing/Invalid info "),
  BAD_REQUEST("S-002", "Bad request"), 
  NOT_SUPER_ADMIN("S-003", "Not super admin"),
  FILE_UPLOAD_SUCCESS("S-004", "File uploaded successfully"),
  FILE_UPLOAD_FAIL("S-005", "File upload failed"),
  FILE_UPDATED_SUCCESS("S-006", "File updated successfully"), 
  ENCRYPTION_INVALID("S-007", "Invalid encryption"), 
  ENCRYPTION_EXPIRED("S-008", "Encryption keys invalid"),
  INVALID_ENCRYPTED_DATA("S-009", "Invalid encrypted data"),
  MISSING_CLIENTTRANSACTIONID("S-010", "Missing clientTransactionId"),
  FILE_DOESNT_EXIST("S-011", "File doesn't exist"),
  OAUTH2_EXISTING_CREDENTIALS("S-012", "Existing OAuth credentials"),
  OAUTH2_MISSING_CREDENTIALS("S-013", "Missing OAuth credentials"),
  OAUTH2_INVALID_CLIENTID("S-014", "Invalid OAuth clientId"), 
  EMPTY_REQUEST("S-015", "Empty request"),
  ADMIN_CAN_NOT_ADD_SUPERADMIN("S-016", "Admin user cannot add superadmin"),
  MISSING_ROLE("S-017", "Missing user role"),
  ADD_SUB_USER_ONBOARD("S-018", "User can add super admin or admin sub user only, until status is not activated"),

  DOC_ID_NOT_FOUND("S-019", "Invalid document Id"),
  DOC_TYPE_NOT_FOUND("S-020", "Invalid document type"),
  DATA_NOT_FOUND("S-021", "Data not found"),
  ADMIN_CAN_NOT_DELETE_SUPERADMIN("S-022", "Admin user cannot delete superadmin"),
  MISSING_INVALID_AMC_METHOD("S-023", "Invalid payment method"),
  MISSING_INVALID_FEES_TYPE("S-024", "Invalid fees type"), 
  MISSING_INVALID_PAYMENT_REF_NUM("S-025","Missing/Invalid payment reference number"),
  MISSING_PAYMENT_AMOUNT("S-026", "Missing/Invalid payment amount"), 
  PAYMENT_CAPTURED("S-027", "Payment details captured"),
  MISSING_INVALID_PAYMENT_REF_DATE("S-028", "Missing/Invalid payment reference date"),
  INVALID_DOMAINS_NAME("S-029", "Invalid domain name"),
  INVALID_SOURCE("S-030", "Invalid source provided"),
  SOURCE_NOT_FOUND("S-031", "Invalid source type"),
  INVALID_TRANSACTION_SOURCE("S-032", "Invalid transaction source"),
  ADMIN_CAN_NOT_CHANGE_ROLE_SUPERADMIN("S-033", "Admin user cannot change role of superadmin"),
  FAILED("S-034","Failed transaction"),
  SUCCESS("S-035","Successful transaction"),
  FAIL_TO_FETCH_DIPCOIN_TRANSACTION("S-036","Please try again, we are unable to fetch your dipcoin transaction"),
  ADD_BILLER_INFORMATION_SUCCESS("S-037","Added biller information successfully"),
  DUPLICATE_BILLER_INFORMATION("S-038","Duplicate entry for biller"),
  MISSING_INVALID_CUSTOMIZATION("S-039","Missing or Invalid api customization"),
  DUPLICATE_API_CUSTOMIZATION("S-040", "Duplicate API Customization Method"),
  ACCESS_FORBIDDEN("S-041", "Access Forbidden"),
  OFFLINE_BAD_REQUEST("S-042", "Bad request from offline system"),
  MISSING_SELECTION_OF_SCHEMA("S-043" , "Missing schema selection."),
  MISSING_SELECTION_OF_SCHEMA_AND_TABLENAME("S-044" , "Missing schema and tablename selection"),   
  TABLE_NAME_MISSING("S-045", "Table name cannot be empty"),
  MISSING_INVALID_TABLE_COLUMNS("S-046", "Missing or invalid table columns"),
  NO_DATA_AVAILABLE("S-047", "No data available"),
  INCORRECT_OFFLINE_STARTTIME("S-048", "Please check start time value"),
  INCORRECT_OFFLINE_ENDTIME("S-049", "Please check end time value"),
  INVALID_EPOCHTIME("S-050", "Invalid epochtime"),
  BANK_NOT_ACTIVATED("S-51", "Bank is not activated to do business."),
  MERCHANT_NOT_ACTIVATED("S-52", "Merchant is not activated to do business."),
  DATA_UPDATE_SUCCESS("S-053", "Data uploaded successfully"),
  DATA_UPDATE_FAILED("S-054", "Data upload failed"),
  MISSING_INVALID_PHONE_ALIAS("S-055", "Missing or Invalid Phone Alias"),
  MISSING_INVALID_AGENTID("S-056", "Missing or Invalid AgentId"),
  MISSING_INVALID_AGENT("S-057", "Missing or Invalid Agent"),
  DUPLICATE_REQUEST("S-058", "Duplicate request"),
  UPDATED_AGENT_DETAILS("S-059","Agent details updated successfully."),
  UPDATE_BRANCH_CODE_FILE_HEADER_NOT_MATCHED("S-060","Branch Code file header name not found"),
  UPDATE_PHONE_NUMBER_FILE_HEADER_NOT_MATCHED("S-061","Phone number file header name not found"),
  NO_ACTIVE_LIEN("S-062","No Active Lien"),
  HEADER_NOT_FOUND("S-063", "Header not available"),
  FILE_READ_SUCCESS("S-064","File read success"),
  COMPLAINT_ALREADY_RAISED("S-066", "Complaint already initiated"),

  

//Toll customer error code range TC-<001-013> - toll customer code
  TOLL_USER_INVALID_FNAME("TC-001", "Invalid first name"),
  TOLL_USER_INVALID_LNAME("TC-002", "Invalid last name"),
  TOLL_USER_INVALID_GENDER("TC-003", "Invalid gender"),
  TOLL_USER_INVALID_DOB("TC-004", "Invalid dob"),
  TOLL_USER_INVALID_MOBILE("TC-005", "Invalid mobile number"),
  TOLL_USER_INVALID_EMAIL("TC-006", "Invalid email"),
  TOLL_USER_INVALID_ADDRESS("TC-007", "Invalid Address"),
  TOLL_USER_INVALID_CITY("TC-008", "Invalid City"),
  TOLL_USER_INVALID_STATE("TC-009", "Invalid State"),
  TOLL_USER_INVALID_PINCODE("TC-010", "Invalid Pincode"),
  TOLL_USER_INVALID_IDPROOFTYPE("TC-011", "Invalid IdProofType"),
  TOLL_USER_INVALID_IDPROOFNO("TC-012", "Invalid IdProofNo"),
  TOLL_USER_INVALID_IDPROOFPATH("TC-013", "Invalid IdProffPath"),
  TOLL_ACCOUNT_DOESNT_EXIST("TC-014", "Toll Account doesn't exist"),	
  TOLL_USER_DETAILS_CANNOT_UPDATE("TC-015", "Toll customer details cannot be updated"),	
  TOLL_USER_DETAILS_UPDATED("TC-016", "Toll customer details updated"),
  TOLL_NETC_VERIFICATION_FAIL("TC-017","Information provided could not be verified with NETC FASTag system."),
  TOLL_TAG_INACTIVE("TC-018","Toll Tag is INACTIVE"),
  TOLL_REGISTRATION_INACTIVE("TC-019","Toll Profile Successfully Deactivated"),
  TOLL_RECHARGE_SUCCESS("TC-020","Tag has been recharged successfully"),
  TOLL_RECHARGE_FAILURE("TC-021","Tag has low balance, please recharge"),
  TOLL_TAG_DOESNT_EXIST("TC-022", "Tag doesn't exist"),
  TOLL_TAG_RFID_GENERATED("TC-023", "Tag has been generated successfully."),
  TOLL_IIN_SERIAL_SIZE("TC-024", "Serial number size should be 7. (Serial number is followed by IIN and Vehicle category)."),
  TOLL_TAG_ALREADY_GENERATED("TC-025", "Some Rfid Tag are already present / generated in system."),
  TOLL_TAG_SERIAL_NUMBER_NOT_CORRECT("TC-026", "Tag serial number is not correct."),
  TOLL_TAG_NOT_GENERATED("TC-027", "Toll Tag could not be generated."),
  TOLL_INACTIVE_ACCOUNT_UPDATION("TC-028", "Toll inactive account has been updated"),
  INVALID_CUSTOMER_BANK_CODE("TC-029", "Invalid Bank Code"),
  INVALID_CUSTOMER_TAGID("TC-030", "Invalid Tag ID"),
  TOLL_DEPOSIT_AND_FEE_AMOUNT_NOT_AVAILABLE("TC-031", "Toll deposit fee and charges are not available in the system."),
  TOLL_TAG_ACTIVATED("TC-032","Toll tag activated successful"),
  TOLL_TAG_MAXIMUM_POSSIBLE_SERIAL_NUMBER_GENERATED("TC-033", "Maximum Possible Serial Number Generated"),
  TOLL_TAG_GENERATION_NOT_ALLOWED("TC-034", "Tag Generation Not Allowed Till 10% of Tag Is Used"),
  TOLL_TAG_GENERATION_COUNT_CONSTRAINT("TC-035", "Only 5000 Tags Can Be Generated At One Time"),
  TOLL_TAG_APPROVAL_PENDING("TC-036", "Some Associated Tag Are Pending for Approval So Amount Cannot Be Released"),
  TOLL_ALL_TAG_ACTIVE("TC-037", "There is / are active Tags and hence amount cannot be released."),
  TOLL_TAG_GENERATION_MAXIMUM_LIMIT_REACHED("TC-038", "Some Tag Generated And Some Are Not as Maximum Limit Reached"),
  TOLL_BANK_STATUS_NOT_ACTIVE("TC-039", "Selected Bank does not support FASTag as of now."),
  TOLLTAG_SETTLEMENT_PENDING("TC-040","Toll Tag Osta settlement pending, please try after 24-48 hours."),
  TOLLTAG_TID_UPDATION_SIGNATURE_GENERATION_STARTED("TC-041","TollTag Tid Updation And Signature Generation Started"),
  TOLL_TAG_DETAILS_MAILED("TC-042","Toll Tag Details Have been Mailed"),
  TOLL_BANK_IIN_NOT_SET("TC-043", "Toll Bank IIN is Not Set"),
  TOLL_API_NOT_ALLOWED("TC-044", "This api access is not allowed in this environment"),
  TOLL_USER_VEHICLE_NUMBER_ALREADY_EXIST("TC-045", "Vehicle has already been registered in system."),
  TOLL_IHMCL_USER_VEHICLE_VERIFICATION_FAILED("TC-046", "Vehicle registration number could not be verified."),
  TOLL_VEHICLE_REG_NO_NOT_PRESENT("TC-047", "Vehicle registration number is not present"),
  TOLL_VEHICLE_REG_NO_NOT_ASSOCIATED_WITH_ACCOUNT("TC-048", "Vehicle registration number not associated with this account or account number is not available."),
  TOLL_ISSUER_CANNOT_BE_APPROVER("TC-049", "Issuer (Maker) of FASTag cannot be approver. Please request supervisor (checker) to approve."),
  TOLL_PREVIOUSLY_ISSUED_TAG_IS_INVALID("TC-050", "your previously issued Tag with other bank is blacklisted, please address it with respective bank before activation."),
  TOLL_REGISTRATION_BY_CUSTOMER_SUCCESSFULL("TC-051","Registration successful. Post approval by Bank Tag would be dispatched to your registered addressed in 3-4 working days. Once Tag is received, please login to activate Tag."),
  TOLL_REGISTRATION_BANK_APRROVED("TC-052","Registration successful. Tag would be dispatched to registered addressed in 3-4 working days."),
  TOLL_RECHARGE_SUCCESS_TAG_IN_LOW_BALANCE("TC-053","Toll Tag recharge successful but tag is still in low balance"),
  TOLL_SERIAL_NUMBER_USED("TC-054","Serial Number was used select another one"),
  TOLL_VEHICLE_NOT_ACTIVATED("TC-055","Vehicle is Not Active"),
  TOLL_VEHICLE_CUSTOMER_ACTIVATION_PENDING("TC-056","Customer activation pending"),
  TOLL_THRESHOLD_AMOUNT_INCORRECT("TC-057","Auto-topup is active through this payment source. Please fill Auto-topup details to apply for another vehicle through same payment source."),
  TOLL_TAG_DELIVERY_FILE_HEADER_NOT_MATCHED("TC-058", "Toll tag delivery file header name not found"),
  TOLL_TAG_PROFILE_ALREADY_ACTIVATED("TC-059", "FASTag profile already activated"),
  TOLL_TAG_DELIVERY_FILE_SERIAL_NOT_MATCHED_WITH_BANK("TC-060", "Toll tag delivery file had some serial number which did not match with bank"),
  TOLL_TAG_DELIVERY_FILE_READ_SUCCESS("TC-061", "Toll tag delivery file read successfully"),
  TOLL_TAG_IMAGE_MISSING("TC-062", "Image is missing"),
  TOLL_TAG_PROFILE_ALREADY_SELECTED_FOR_APPROVAL("TC-063", "Toll Tag profile already selected for approval by other sub user of bank"),
  TOLL_TAG_SERIAL_NUMBER_ALREADY_SELECTED_FOR_APPROVAL("TC-064", "Toll Tag Serial number  already selected for approval by other sub user of bank"),
  TOLL_TAG_VEHICLE_NUMBER_REGISTRATON_IN_PROGRESS_TRY_LATER("TC-065", "Vehicle number registration validation already is in progress. Try after few minutes."),
  TOLL_TAG_SERIAL_NUMBER_NOT_APPROVED_YET("TC-066","Serial number is not Approved yet"),
  TOLL_TAG_UPDATION_FAILS("TC-067", "Toll tag updation fails"),
  TAG_ID_ALREADY_USED("TC-068", "Toll TagId already used."),
  EPC_CATEGORY_MISMATCH("TC-069", "Category is not matching."),
  MISSING_EPC_DATA("TC-070", "Serial number not correct"),
  TAG_ID_ALREADY_PRESENT("TC-071", "Toll TagId already present."),
  TID_ALREADY_PRESENT("TC-072", "Tid already present."),
  BOTH_TAGID_TID_MUST_BE_PRESENT("TC-073", "Both TagId and Tid must be present in combination."),
  BOTH_ADDTAGRESPONSE_ADDTAGERRORCODE_MUST_BE_PRESENT("TC-073", "Both AddTagResponse and AddTagErrorCode must be present in combination."),
  FAILED_TO_UPDATE_TOLLTAG_DETAILS("TC-074", "Failed to update TollTag Details."),
  FAILED_TO_UPDATE_EPC_DETAILS("TC-075", "Failed to update Epc table details."),
  TOLL_TAG_REQUET_PAY_FAILED("TC-076", "Vehicle either in low-balance or blacklisted."),
  TRANSACTION_NOT_FOUND("TC-077", "Transaction not found."),
  TOLL_TRANSACTION_MAILED("TC-078","Toll Transaction will be Mailed"),
  TOLL_TRANSACTION_NOT_MAILED("TC-079","Toll Transaction Not Mailed"),
  TOLL_REGISTRATION_NOT_UPDATED("TC-080","Failed to update toll registration details"),
  TOLL_TAG_REDELIVERY_REASON_MISSING("TC-081","Tolltag redelvery reason missing"),
  TOLL_REGISTRATION_DOESNT_EXIST("TC-082","TOLL registration doesn't exists"),
  TOLL_RECON_ACCOUNTING_MAILED("TC-083","Toll Recon/Accounting mailed, check in spam if not received"), 
  TOLL_REGISTRATION_SUCCESSFUL_TAG_ASSIGNMENT_PENDING("TC-084","Registration successful. Tag Assignment pending"),
  TOLL_VEHICLE_REG_NO_NOT_ASSOCIATED_WITH_BANK("TC-085","Vehicle registration number not associated with this Bank or Vehicle Registration number is not available."),
  EPC_DETAILS_UPDATED("TC-086","Epc details updated"),
  SERIES_NOT_AVAILABLE_WITH_COUNT("TC-087","Series is not available for the given count"),
  WRONG_VIN_NUMBER_AND_SERIAL_NUMBER_INPUT("TC-088","wrong vin number and serial number entered"),
  ALREADY_VERIFIED_THE_DETAILS("TC-089","already verified the details"),
  TOLL_TAGS_NOT_FOUND("TC-090","Toll Tags not found"),
  ORDER_ID_ALREADY_PRESENT("TC-091","Entry with given Order Id already present"),
  SUCCESS_TO_UPDATE_TOLLTAG_DETAILS("TC-092","Successfully Updated TollTagDetails"),
  TOLL_TAG_APPROVED("TC-093","Successfully TollTag Approved"),
  TOLL_TAG_NOT_APPROVED("TC-093","UnSuccess to Approved  TollTag "),
  BULK_HOTLIST_STARTED("TC-0930","Bulk Hotlist Job Started"),
  BULK_LIEN_REMOVE_STARTED("TC-0931","Bulk Lien Remove Job Started"),
  TAG_SENT_FOR_UPDATION("TC-0932","Tag sent for updation"),

  REQUEST_TIMEOUT("S-997", "Request timed out"),
  REQUEST_OK("S-998", "Ok"),
  INTERNAL_ERROR("S-999", "Internal Error"),
	
  //Transaction Error codes 
  TRANSACTION_SUCCESSFUL("P-000","Transaction Successful"),
  TRANSACTION_FAILURE("P-001","Transaction Failure"),
  INVALID_CHECKSUM("P-002","Invalid Checksum"),
  CHECKSUM_MISSING("P-003","Checksum Missing"),
  INVALID_TOKEN("P-004","Invalid token"),
  EXPIRED_TOKEN("P-005", "Token Expired"),
		
  WALLET_CREATED("W-001", "Wallet created"),
  WALLET_Not_CREATED("W-002", "Wallet unable to create"),
  WALLET_TOPUP_SUCCESSFUL("W-003", "Money added successful"),
  WALLET_TOPUP_FAILED("W-004", "Wallet topup failed"),
  WALLET_BALANCE_FETCH_SUCCESSFUL("W-005", " Wallet balance successfully fetched"),
  WALLET_BALANCE_FAILED_TO_FETCH("W-006", "Unable to fetch wallet balance"),
  WALLET_PAYMENT_SUCCESS("W-007", "Payment Successful"),
  WALLET_PAYMENT_FAILED("W-008", "Payment failed"),
  WALLET_MONEY_TRANSFER_SUCCESS("W-009", "Transfer is been initiated will reflect in your bank account within 2 to 3 working days"),
  WALLET_DELETE_SUCCESS("W-011", "Wallet got deleted Successfully"),
  WALLET_CANT_BE_DELETED("W-012", "Wallet can't be deleted"),
  WALLET_TRANSACTION_STATUS_SUCCESS("W-013", "transaction successful"),
  WALLETID_MISSING("W-014","Wallet Id missing"),
  WALLET_TRANSACTION_NOT_FOUND("W-015", "Wallet transaction not found"),
	  
  //Toll codes
  VERSION_EMPTY_OR_NOT_1_0("N-101","Version Empty or not 1.0"),
  TIMESTAMP_EMPTY_OR_NOT_IN_ISO_FORMAT("N-102","Timestamp empty or not in ISO Format"),
  ORGID_IS_NOT_AVAILABLE_IN_DATABASE("N-103","orgId is not available in Database"),
  MSGID_IS_NOT_IN_CORRECT_FORMAT_OR_EMPTY("N-104","msgId is not in correct format or empty"),
  TXN_ID_IS_EMPTY_OR_NOT_IN_CORRECT_FORMAT("N-105","Txn Id is empty or not in correct format"),
  TAGID_IS_NOT_IN_CORRECT_FORMAT_OR_EMPTY("N-106","TagId is not in correct format or empty"),
  TAGID_ALREADY_PRESENT_IN_DATABASE("N-107","TagId already present in Database"),
  ORG_ID_IS_EMPTY_OR_NOT_IN_CORRECT_FORMAT("N-108","Org Id is empty or not in correct format"),
  SEQNUM_DUPLICATE_IN_A_REQUEST("N-109","SeqNum duplicate in a request"),
  EMPTY_SEQNUM_OR_NOT_NUMERIC("N-110","Empty SeqNum or not numeric"),
  TID_IS_EMPTY_OR_NOT_IN_CORRECT_FORMAT("N-112","TID is empty or not in correct format"),
  VEHICLE_CLASS_IS_EMPTY_OR_NOT_IN_CORRECT_FORMAT("N-113","Vehicle Class is empty or not in correct format"),
  VEHICLE_CLASS_NOT_AVAILABLE_IN_DATABASE("N-114","Vehicle class not available in Database"),
  REGNO_EMPTY_OR_NOT_IN_CORRECT_FORMAT("N-115","RegNo empty or not in correct format"),
  BANK_ID_IS_EMPTY_OR_NOT_IN_CORRECT_FORMAT("N-116","Bank ID is empty or not in correct format"),
  EXCEPTION_CODE_IS_EMPTY_OR_NOT_IN_CORRECT_FORMAT("N-118","Exception code is empty or not in correct format"),
  EXCEPTION_CODE_NOT_IN_DATABASE("N-119","Exception code not in Database"),
  ISSUE_DATE_IS_EMPTY_OR_NOT_IN_CORRECT_FORMAT("N-122","Issue Date is empty or not in correct format"),
  ISSUE_DATE_SHOULD_NOT_BE_GREATER_THAN_CURRENT_DATE("N-123","Issue Date should not be greater than current date"),
  ORGID_IS_INACTIVE("N-124","OrgId is Inactive"),
  TAGID_IS_NOT_PRESENT_IN_DATABASE("N-125","TagId is not present in Database"),
  AMOUNT_EMPTY_OR_NOT_IN_CORRECT_FORMAT("N-126","Amount empty or not in correct format"),
  PLAZA_CODE_EMPTY_OR_NOT_IN_CORRECT_FORMAT("N-127","Plaza code empty or not in correct format"),
  VIN_TYPE_FIELD_IN_MANAGETAG__IS_NOT_IN_CORRECT_FORMAT("N-131","VIN(Type field in Managetag) is not in correct format"),
  TAGID_NOT_ASSOCIATED_WITH_ISSUER_BANK("N-132","TagId not associated with issuer Bank"),
  COUNTER_IS_EMPTY_OR_NOT_IN_CORRECT_FORMAT("N-133","Counter is empty or not in correct format"),
  NOT_ABLE_TO_REACH_DATABASE("N-134","Not able to reach Database"),
  NOT_ABLE_TO_CONTACT_ISSUER("N-136","Not able to contact issuer"),
  TOLL_EMPTY_REQUEST("N-138","Empty Request"),
  HEAD_ELEMENT_IS_NOT_AVAILABLE("N-139","Head Element is not available"),
  TRANSACTION_ELEMENT_IS_NOT_AVAILABLE("N-140","Transaction Element is not available"),
  NOTE_IS_NOT_IN_CORRECT_FORMAT("N-141","Note is not in correct format"),
  REFID_IS_NOT_IN_CORRECT_FORMAT("N-142","RefId is not in correct format"),
  REFURL_IS_NOT_IN_CORRECT_FORMAT("N-143","RefUrl is not in correct format"),
  TXN_TYPE_IS_EMPTY_OR_NOT_IN_THE_LIST_OF_TYPES("N-144","Txn Type is empty or not in the list of types"),
  VEHICLE_TAG_IS_NULL("N-145","Vehicle Tag is null"),
  INPUTS_ARE_NULL_TO_UPDATE("N-146","Inputs are null to UPDATE"),
  REQUEST_IS_NOT_IN_CORRECT_FORMAT("N-147","Request is not in correct format"),
  OP_CODE_IS_EMPTY("N-148","OP code is empty"),
  OP_CODE_IS_INCORRECT("N-149","OP code is incorrect"),
  LANE_READER_ID_IS_EMPTY_OR_NOT_IN_CORRECT_FORMAT("N-150","Lane Reader ID is empty or not in correct format"),
  ERROR_IN_INSERTION_IN_TABLE("N-151","Error in insertion in table"),
  EXCEPTION_CODE_ALREADY_MAPPED_WITH_TAGID("N-155","Exception code already mapped with TagId"),
  GIVEN_EXCEPTION_CODE_NOT_AVAILABLE_IN_TAGID_TO_REMOVE("N-157","Given exception code not available in TagId to remove"),
  LAST_FETCH_TIME_IS_GREATER_THAN_24_HOURS_OR_FUTURE_TIME("N-159","Last Fetch Time is greater than 24 hours or future time"),
  LAST_FETCH_TIME_IS_EMPTY_OR_NOT_IN_CORRECT_FORMAT("N-160","Last fetch time is empty or not in correct format"),
  RISK_SCORE_PROVIDER_IS_EMPTY_OR_IS_NOT_IN_CORRECT_FORMAT("N-161","Risk Score Provider is empty or is not in correct format"),
  RISK_SCORE_TYPE_IS_EMPTY_OR_NOT_IN_CORRECT_FORMAT("N-162","risk score type is empty or not in correct format"),
  RISK_SCORE_VALUE_IS_EMPTY_IS_NOT_IN_CORRECT_FORMAT("N-163","risk score value is empty is not in correct format"),
  TID_ID_NOT_MAPPED_WITH_GIVEN_TAGID("N-164","TID ID not mapped with given tagId"),
  AVC_NOT_IN_CORRECT_FORMAT("N-165","AVC not in correct format"),
  PLAZA_NAME_NOT_IN_CORRECT_FORMAT("N-166","Plaza name not in correct format"),
  PLAZA_GEOCODE_IS_EMPTY_OR_NOT_IN_CORRECT_FORMAT("N-167","Plaza geocode is empty or not in correct format"),
  PLAZA_TYPE_IS_EMPTY_OR_NOT_IN_CORRECT_FORMAT("N-168","Plaza type is empty or not in correct format"),
  LANE_ID_IS_EMPTY_OR_NOT_IN_CORRECT_FORMAT("N-169","Lane Id is empty or not in correct format"),
  LANE_DIRECTON_IS_EMPTY_OT_NOT_IN_CORRECT_FORMAT("N-170","Lane Directon is empty ot not in correct format"),
  READER_READ_TIME_IS_EMPTY_OR_NOT_IN_CORRECT_FORMAT("N-171","Reader Read time is empty or not in correct format"),
  READER_READ_TIME_CANNOT_BE_MORE_THAN_TXN_TIME("N-172","Reader Read Time cannot be more than txn time"),
  MAXIMUM_DAYS_TO_PUSH_OLDER_TRANSACTIONS_EXCEEDS("N-173","Maximum days to push older transactions exceeds(defaulf-Current Time is more than 3 days from reader read time)"),
  ORGTXNID_IS_NOT_IN_CORRECT_FORMAT("N-174","orgTxnId is not in correct format"),
  AMOUNT_SHOULD_BE_ZERO_AS_TAGID_IS_IN_EXEMPTION_CODE("N-175","Amount should be zero as tagId is in exemption Code"),
  CANNOT_INITIATE_TXN_AS_TAG_IS_IN_BLACK_LIST_OR_LOW_BALANCE_LIST("N-176","Cannot initiate TXN as Tag is in Black List or Low Balance List"),
  DUPLICATE_EXCCODE("N-177","Duplicate ExcCode"),
  PLAZA_NOT_AVAILABLE_IN_DATABASE("N-178","Plaza not available in Database"),
  PLAZA_NOT_ASSOCIATED_WITH_ACQUIRER_ID("N-179","Plaza not associated with Acquirer ID"),
  PLAZA_TYPE_IS_NOT_SAME_AS_AVAILABLE_IN_DB("N-180","Plaza type is not same as available in DB"),
  LANE_ATTRIBUTES_SHOULD_BE_EMPTY_IN_CASE_OF_PLAZA_TYPE_AS_PARKING("N-181","Lane attributes should be empty in case of Plaza type as Parking"),
  PARKING_FLOOR_IS_EMPTY_OR_NOT_IN_CORRECT_FORMAT("N-182","Parking floor is empty or not in correct format"),
  PARKING_ZONE_IS_EMPTY_OR_NOT_IN_CORRECT_FORMAT("N-183","Parking zone is empty or not in correct format"),
  SLOT_ID_IS_EMPTY_OR_NOT_IN_CORRECT_FORMAT("N-184","Slot Id is empty or not in correct format"),
  READER_ID_IS_EMPTY_OR_NOT_IN_CORRECT_FORMAT("N-185","Reader Id is empty or not in correct format"),
  VEHICLE_DETAILS_ARE_NOT_IN_CORRECT_FORMAT("N-186","VEHICLE DETAILS are not in correct format"),
  VEHICLE_CLASS_IS_NOT_ASSOCIATED_WITH_TAGID("N-187","Vehicle Class is not associated with tagId"),
  REG_NO_IS_NOT_ASSOCIATED_WITH_TAGID("N-188","Reg no. is not associated with tagId"),
  STATUS_IS_NOT_ASSOCIATED_WITH_TAGID("N-189","Status(A/I) is not associated with tagId."),
  ISSUEDATE_IS_NOT_ASSOCIATED_WITH_TAGID("N-190","issueDate is not associated with tagId"),
  EXCCODE_IS_NOT_ASSOCIATED_WITH_TAGID("N-191","ExcCode is not associated with tagId"),
  PAYER_ADDR_IS_EMPTY_OR_NOT_IN_CORRECT_FORMAT("N-193","Payer addr is empty or not in correct format"),
  PAYER_NAME_IS_NOT_IN_CORRECT_FORMAT("N-194","Payer Name is not in correct format"),
  PAYER_TYPE_SHOULD_BE_PERSON("N-195","Payer type should be PERSON"),
  CURRENCY_IS_EMPTY_OR_NOT_IN_CORRECT_F11ORMAT("N-196","Currency is empty or not in correct f11ormat"),
  PAYEE_ADDR_IS_EMPTY_OR_NOT_IN_CORRECT_FORMAT("N-197","Payee Addr is empty or not in correct format"),
  AVC_NOT_IN_DB("N-198","Avc Not in DB"),
  PAYEE_NAME_IS_NOT_IN_CORRECT_FORMAT("N-199","Payee Name is not in correct format"),
  PAYEE_TYPE_SHOULD_BE_MERCHANT("N-200","Payee Type should be MERCHANT"),
  TRANSACTION_ID_MERCHANT_ID_ACQUIRER_ID_SHOULD_BE_UNIQUE_FOR_A_TRANSACTION("N-201","Transaction ID Merchant ID Acquirer ID should be unique for a transaction"),
  META_ELEMENT_IS_MISSING("N-202","Meta Element is missing"),
  AMOUNT_SHOULD_BE_ZERO_IF_TXN_TYPE_IS_NON_FIN("N-203","Amount should be zero if txn type is NON_FIN"),
  TID_SHOULD_BE_UNIQUE("N-204","TID should be Unique"),
  FUTURE_TIMESTAMP_SHOULD_NOT_BE_ACCEPTABLE("N-205","Future Timestamp should not be acceptable"),
  NOT_ALLOWED_TO_USE_PARTICULAR_SERVICE("N-206","Not allowed to use particular service"),
  EXCEPTION_CODE_IS_ALREADY_ADDED_BY_OTHER_BANK("N-207","Exception Code is already added by other bank"),
  NO_PRIVLEDGES_TO_ADD_EXCEPTION_CODE("N-208","No privileges to add exception Code"),
  TID_VERIFIED_IS_EMPTY_OR_NOT_IN_CORRECT_FORMAT("N-209","TID Verified is empty or not in correct format"),
  SIGN_DATA_AND_PUBLIC_KEY_CVV_IS_MANDATORY_IF_TID_VERIFIED_IS_NETC_TAG("N-210","Sign Data and Public Key CVV is mandatory if TID verified is netc tag"),
  SIGN_DATA_IS_NOT_IN_CORRECT_FORMAT("N-211","Sign Data is not in correct format"),
  PUBLIC_KEY_CVV_IS_NOT_IN_CORRECT_FORMAT("N-212","Public Key CVV is not in correct format"),
  SIGN_AUTH_IS_NOT_VALID("N-213","Sign Auth is not valid"),
  PROCRESTRICTIONRESULT_IS_NOT_IN_CORRECT_FORMAT("N-214","procRestrictionResult is not in correct format"),
  VEHICLE_AUTH_IS_NOT_VALID("N-215","Vehicle Auth is not valid"),
  TXN_COUNTER_IS_EMPTY_OR_NOT_IN_CORRECT_FORMAT("N-216","Txn Counter is empty or not in correct format"),
  TXN_STATUS_IS_EMPTY_OR_NOT_IN_CORRECT_FORMAT("N-217","Txn Status is empty or not in correct format"),
  TXN_AMOUNT_SHOULD_BE_ZERO_IF_TXN_STATUS_IS_FAILED("N-218","Txn Amount should be zero if txn status is FAILED"),
  PARKING_DETAILS_SHOULD_BE_EMPTY_IF_PLAZA_TYPE_IS_NOT_PARKING("N-219","Parking details should be empty if Plaza Type is not Parking"),
  PAYEE_ADDRESS_IS_INCORRECT("N-220","Payee Address is incorrect"),
  HEART_BEAT_MSG_TYPE_IS_NOT_IN_PREDEFINED_TYPES("N-221","Heart Beat Msg Type is not in predefined types"),
  HEART_BEAT_MSG_ACQUIRER_ID_IS_NOT_MATCHED_WITH_ORGID_ACQUIRER_ID("N-222","Heart Beat msg Acquirer Id is not matched with OrgId's acquirer Id"),
  PARKING_STATUS_IS_EMPTY_OR_NOT_IN_CORRECT_FORMAT("N-223","Parking status is empty or not in correct format"),
  AVAILABLE_SLOT_IS_EMPTY_OR_NOT_IN_CORRECT_FORMAT("N-224","Available slot is empty or not in correct format"),
  LANE_STATUS_IS_EMPTY_OR_NOT_IN_CORRECT_FORMAT("N-225","Lane status is empty or not in correct format"),
  COMVEHICLE_IS_EMPTY_OR_NOT_IN_CORRECT_FORMAT("N-231","Comvehicle is Empty or not in correct format"),
  TID_IS_NOT_IN_DB("N-232","TID is not in DB"),
  VEHICLE_REG_NO_NOT_IN_DB("N-233","Vehicle Reg No not in DB"),
  ANY_ONE_INPUT_EITHER_TAGID_OR_TID_OR_VEHICLEREGNO_SHOULD_BE_PRESENT_FOR_REQUEST_TAG_DETAILS("N-234","Any one input either tagid or TID or vehicleRegNo should be present for Request Tag Details"),
  PLAZA_SUBTYPE_IS_EMPTY_OR_NOT_IN_CORRECT_FORMAT("N-235","Plaza Subtype is empty or not in correct format"),
  PLAZA_SUBTYPE_IS_NOT_SAME_AS_AVAILABLE_IN_DB("N-236","Plaza Subtype is not same as available in DB"),
  COMMERCIAL_VEHICLE_FLAG_IS_NOT_SAME_IN_DB("N-237","Commercial Vehicle Flag is not same in DB"),
  IIN_FROM_TAGID_IS_NOT_MATCHING_WITH_ORGID_IIN("N-238","IIN from TagId is not matching with orgid's IIN"),
  ONLY_ONE_INPUT_IS_ALLOWED_EITHER_TAGID_OR_TID_OR_VEHICLEREGNO("N-239","Only one input is allowed either tagid or TID or vehicleRegNo"),
  VEHICLE_REGNO_OR_VIN_OR_ENGINENUMBER_ALREADY_REGISTERED_WITH_SOME_OTHER_TAGID("N-240","Vehicle RegNo or Vin or EngineNumber Already Registered with some other TagId."),
  ONE_OR_MORE_ATTRIBUTE_IS_MISSING_IN_HEAD_ELEMENT("N-241","One or more attribute is missing in Head Element"),
  ONE_OR_MORE_ATTRIBUTE_IS_MISSING_IN_TXN_ELEMENT("N-242","One or more attribute is missing in Txn Element"),
  ONE_OR_MORE_ATTRIBUTE_IS_MISSING_IN_TAGLIST("N-243","One or more attribute is missing in TagList"),
  ONE_OR_MORE_ATTRIBUTE_IS_MISSING_IN_META_ELEMENT("N-244","One or more attribute is missing in Meta Element"),
  ONE_OR_MORE_ATTRIBUTE_IS_MISSING_IN_MERCHANT_ELEMENT("N-245","One or more attribute is missing in Merchant Element"),
  ONE_OR_MORE_ATTRIBUTE_IS_MISSING_IN_VEHICLE_ELEMENT("N-246","One or more attribute is missing in Vehicle Element"),
  ONE_OR_MORE_ATTRIBUTE_IS_MISSING_IN_PAYER_ELEMENT("N-247","One or more attribute is missing in Payer Element"),
  ONE_OR_MORE_ATTRIBUTE_IS_MISSING_IN_PAYEE_ELEMENT("N-248","One or more attribute is missing in Payee Element"),
  PAYER_ADDRESS_IS_INCORRECT("N-249","Payer Address is incorrect"),
  ONE_OR_MORE_ATTRIBUTE_IS_MISSING_IN_EXCEPTION_TAG("N-250","One or more attribute is missing in Exception tag"),
  SIGNATURE_IS_NOT_FOUND_IN_REQUEST("N-261","Signature is not found in request"),
  BANK_CERTIFICATE_IS_NOT_FOUND("N-262","Bank certificate is not found"),
  SIGNATURE_IS__INVALID("N-263","Signature is  invalid"),
  IIN_FROM_TAG_ID_DOES_N0T_MATCH_PAYER_IIN("N-264","IIN from Tag Id doesn't match payer IIN"),
  PARTICIPANT_IS_NOT_AVAILABLE_WITH_GIVEN_ISSUER_ID("N-265","Participant is not available with given issuer ID"),
  MERCHANT_ELEMENT_NOT_AVAILABLE("N-266","Merchant Element not available"),
  LANE_ELEMENT_IS_NOT_AVAILABLE("N-267","Lane Element is not available"),
  PARKING_ELEMENT_IS_NOT_AVAILABLE("N-268","Parking Element is not available"),
  READER_VERIFICATION_RESULT_ELEMENT_IS_NOT_AVAILABLE("N-269","Reader Verification Result Element is not available"),
  PAYEE_ELEMENT_IS_NOT_AVAILABLE("N-270","Payee Element is not available"),
  PAYER_ELEMENT_IS_NOT_AVAILABLE("N-271","Payer Element is not available"),
  AMOUNT_ELEMENT_IS_NOT_AVAILABLE("N-272","Amount Element is not available"),
  RISKSCORES_ELEMENT_IS_NOT_AVAILABLE("N-273","Riskscores Element is not available"),
  SCORE_ELEMENT_IS_NOT_AVAILABLE("N-274","Score Element is not available"),
  VEHICLE_ELEMENT_IS_NOT_AVAILABLE("N-275","Vehicle Element is not available"),
  VEHICLE_DETAILS_ELEMENT_IS_NOT_AVAILABLE("N-276","Vehicle Details Element is not available"),
  TAGLIST_ELEMENT_IS_NOT_AVAILABLE("N-277","TagList Element is not available"),
  TAG_ELEMENT_IS_NOT_AVAILABLE("N-278","Tag Element is not available"),
  EXCEPTIONLIST_ELEMENT_IS_NOT_AVAILABLE("N-279","ExceptionList Element is not available"),
  EXCEPTION_ELEMENT_IS_NOT_AVAILABLE("N-280","Exception Element is not available"),
  AMOUNT_SHOULD_NOT_BE_ZERO_IF_TXN_TYPE_IS_CREDIT_OR_DEBIT("N-281","Amount should not be zero if txn Type is Credit or Debit"),
  ICICI_UNREGISTERED_TAG_DOES_NOT_MATCH_ICICI_IIN("N-282","ICICI Unregistered Tag doesn't match ICICI IIN"),
  ICIC_IIN_IS_NOT_DEFINED("N-283","ICIC IIN is not defined"),
  SIGNATURE_ALGORITHM_IS_NOT_CORRECT("N-284","Signature algorithm is not correct"),
  DIGEST_ALGORITHM_IS_NOT_CORRECT("N-285","Digest algorithm is not correct"),
  QUEUE_FULL("N-286","Queue Full"),
  UNREADABLE_XML("N-287","Unreadable XML"),
  ORGTXNID_CANNOT_BE_NULL_IN_CASE_TXN_TYPE_IS_CREDIT("N-288","OrgTxnId cannot be null in case txn type is CREDIT"),
  CANNOT_INTIATE_SAME_TAGID_FOR_SAME_EXCEPTION_IN_SINGLE_REQUEST("N-289","Cannot Intiate same TagId for Same Exception in Single Request."),
  CREDIT_HAPPENED_ALREADY_FOR_SPECIFIED_TXNID("N-290","Credit Happened Already for Specified TxnId."),
  CREDIT_AMOUNT_SHOULD_NOT_BE_GREATER_THAN_OR_EQUAL_TO_DEBIT_AMOUNT("N-291","Credit amount should not be greater than or equal to debit amount."),
  CREDIT_READER_READ_TIME_SHOULD_NOT_BE_LESS_THAN_DEBIT_READER_READ_TIME("N-292","Credit Reader read time should not be less than Debit Reader read time"),
  NO_TXN_HAPPENED_FOR_DEBIT_IN_LAST_THREE_DAYS("N-293","No Txn happened for debit in last three days"),
  SIGNDATA_SHOULD_BE_MANDATORY_FOR_VERSION_2_0("N-294","SignData should be mandatory for version 2.0"),
  NO_MATCHING_ECC_PUBLICKEY_FOUND_FOR_ISSUER_IIN_AND_KEY_INDEX("N-295","No Matching ECC PublicKey found for Issuer IIN and Key Index"),
  TAG_SIGNATURE_VERIFICATION_FAILED("N-296","Tag Signature Verification Failed"),
  PUBLICKEY_CVV_OF_INPUT_MESSAGE_NOT_MATCHED_WITH_DB_VALUE("N-297","PublicKey CVV of Input Message NOT matched with DB value"),
  TXN_STATUS_SHOULD_NOT_BE_FAILED("N-299","Txn Status Should Not Be Failed"),
  ONE_OR_MORE_ATTRIBUTE_IS_MISSING_IN_STATUS_ELEMENT("N-301","One or more attribute is missing in Status Element"),
  STATUS_ELEMENT_IS_NOT_AVAILABLE("N-302","Status Element is not available"),
  INCORRECT_FORMAT_FOR_TRANSACTION_DATE("N-303","Incorrect format for Transaction Date"),
  TRANSACTION_DATE_IS_OF_FUTURE_DATE("N-304","Transaction Date is of future date"),
  THE_GIVEN_COMBINATION_FOR_A_PARTICULAR_TRANSACTION_DOES_NOT_EXIST("N-305","The given combination for a particular transaction doesn't exist"),
  TRANSACTION_ID_DOES_NOT_EXIST_IN_TRANSACTION_MASTER_TABLE("N-306","Transaction ID doesn't exist in Transaction Master table"),
  TXNID_IN_STATUS_ELEMENT_IS_EMPTY_OR_NOT_IN_CORRECT_FORMAT("N-307","TxnId in Status element is empty or not in correct format"),
  ACQUIRER_ID_IS_EMPTY_OR_NOT_IN_CORRECT_FORMAT("N-308","Acquirer ID is empty or not in correct format"),
  TRANSACTION_STATUS_REQUEST_LIST_ELEMENT_IS_MISSING("N-309","Transaction Status Request List element is missing"),
  DUPLICATE_STATUS_ELEMENT("N-310","Duplicate Status element"),
  STATUS_TAG_SIZE_EXCEEDS_THAT_OF_SYSTEM_PARAMETER_VALUE("N-311","Status tag size exceeds that of system parameter value"),
  PARTICIPANT_LIST_ELEMENT_IS_NOT_AVAILABLE("N-312","Participant List element is not available"),
  PARTICIPANT_ELEMENT_IS_NOT_AVAILABLE("N-313","Participant element is not available"),
  ATTRIBUTE_MISSING_IN_PARTICIPANT_ELEMENT("N-314","Attribute missing in Participant element"),
  SHORTCODE_IN_PARTICIPANT_ELEMENT_IS_EMPTY_OR_INCORRECT_FORMAT("N-315","ShortCode in Participant element is empty or incorrect format"),
  SHORTCODE_IN_PARTICIPANT_ELEMENT_IS_NOT_IN_DB("N-316","ShortCode in Participant element is not in DB"),
  MERCHANT_TAG_SIZE_EXCEEDS_THAT_OF_SYSTEM_PARAMETER_VALUE("N-317","Merchant tag size exceeds that of system parameter value"),
  MERCHANTLIST_ELEMENT_IS_NOT_AVAILABLE("N-318","MerchantList element is not available"),
  MERCHANT_ID_AND_MERCHANT_TYPE_COMBINATION_NOT_IN_DATABASE("N-319","Merchant Id and Merchant Type combination not in Database"),
  DUPLICATE_MERCHANT_ELEMENT("N-320","Duplicate Merchant element"),
  SPECIFIC_MERCHANT_IS_NOT_ALLOWED("N-321","Specific Merchant is not allowed"),
  MERCHANT_ID_ALL_IS_NOT_ALLOWED("N-322","Merchant ID ALL is not allowed"),
  PARTICIPANT_TAG_SIZE_EXCEEDS_THAT_OF_SYSTEM_PARAMETER_VALUE("N-324","Participant tag size exceeds that of system parameter value"),
  DUPLICATE_PARTICIPANT_ELEMENT("N-325","Duplicate Participant Element"),
  SPECIFIC_PARTICIPANT_IS_NOT_ALLOWED("N-326","Specific Participant Is not allowed"),
  PARTICIPANT_SHORTCODE_ALL_IS_NOT_ALLOWED("N-327","Participant shortcode ALL is not allowed"),
  DESTINATION_DOES_NOT_SEND_RESPONSE_WITHIN_SLA("N-333","Destination does not send response within SLA"),
  AMOUNT_IS_MORE_THAN_MAXIMUM_AMOUNT_FOR_VEHICLE_CLASS("N-334","Amount is more than maximum amount for vehicle class"),
  DEEMED_ACCEPTED_WITH_ISSUER_LIABILITY("N-888","Deemed accepted with issuer liability"),
  DEEMED_ACCEPTED_WITH_ACQUIRER_LIABILITY("N-999","Deemed accepted with acquirer liability"),
  INVALID_META_NAME("N-335","Invalid Meta Name"),
  INVALID_META_VALUE("N-336","Invalid Meta Value"),
  META_TAGSIZE_EXCEEDS_THAT_OF_SYSTEMPARAMVALUE("N-337","Meta TagSize Exceeds That Of SystemParamValue"),
  RISK_TAGSIZE_EXCEEDS_THAT_OF_SYSTEMPARAMVALUE("N-339","Risk TagSize Exceeds That Of SystemParamValue"),
  ONE_OR_MORE_ATTRIBUTE_IS_MISSING_IN_SCORE_ELEMENT("N-340","One or more attribute is missing in Score Element"),
  TAG_NOT_MAPPED_WITH_LOW_BALANCE("N-341","Tag not mapped with Low Balance"),
  TAG_IN_LOW_BALANCE("N-342","Tag in Low Balance not more than '30' or 'N' days"),
  TAG_CANNOT_BE_REMOVED_FROM_LOWBALANCE__WHILE_IN_HOTLIST("N-343","Tag cannot be removed from LowBalance  while in HotList"),
  NEW_TAG_CANNOT_REGISTER_FOR_VEHICLE_WHICH_ARE_IN_BLACKLIST_OR_HOTLIST("N-344","New tag cannot register for Vehicle which are in Blacklist or Hotlist"),
  NEW_TAG_CANNOT_BE_REGISTERED_WITH_THE_EXCEPTION_CODE_HOTLIST("N-345","New tag cannot be registered with the exception code Hotlist"),
  INACTIVE_VEHICLE_CLASS("N-346","Inactive Vehicle Class"),
  TRANSACTION_AMOUNT_IS_MORE_THAN_THE_DEFINED_THRESHOLD_LIMIT_FOR_THE_VC("N-500","Transaction amount is more than the defined threshold limit for the VC"),
  COMMAND_NAME_IS_EMPTY_OR_INCORRECT("N-501","Command Name is empty or incorrect"),
  COMMAND_TYPE_IS_EMPTY_OR_INCORRECT("N-502","Command Type is empty or incorrect"),
  COMMAND_ID_IS_EMPTY_OR_INCORRECT("N-503","Command Id is empty or incorrect"),
  NUMPARAMS_IS_EMPTY_OR_INCORRECT("N-504","NumParams is empty or incorrect"),
  CALLBACK_IS_INCORRECT("N-505","Callback is incorrect"),
  PARAM_NAME_IS_EMPTY_OR_INCORRECT("N-506","Param Name is empty or incorrect"),
  PARAM_TYPE_IS_EMPTY_OR_INCORRECT("N-507","Param Type is empty or incorrect"),
  PARAM_VALUE_IS_EMPTY_OR_INCORRECT("N-508","Param Value is empty or incorrect"),
  PARAM_LENGTH_IS_EMPTY_OR_INCORRECT("N-509","Param Length is empty or incorrect"),
  NUMOBJECT_IS_EMPTY_OR_INCORRECT("N-510","NumObject is empty or incorrect"),
  OBJECT_NAME_IS_EMPTY_OR_INCORRECT("N-511","Object Name is empty or incorrect"),
  OBJECT_TYPE_IS_INCORRECT("N-512","Object Type is incorrect"),
  NUMITEMS_IS_EMPTY_OR_INCORRECT("N-513","NumItems is empty or incorrect"),
  ITEM_NAME_IS_EMPTY_OR_INCORRECT("N-514","Item Name is empty or incorrect"),
  ITEM_VALUE_IS_EMPTY_OR_INCORRECT("N-515","Item Value is empty or incorrect"),
  ITEM_TYPE_IS_EMPTY_OR_INCORRECT("N-516","Item Type is empty or incorrect"),
  ITEM_LENGTH_IS_INCORRECT("N-517","Item Length is incorrect"),
  RESULT_TIMESTAMP_IS_EMPTY_OR_INCORRECT("N-518","Result TimeStamp is empty or incorrect"),
  RESULT_STATUS_IS_EMPTY_OR_INCORRECT("N-519","Result Status is empty or incorrect"),
  RESULT_CODE_IS_INCORRECT("N-520","Result Code is incorrect"),
  SOURCE_ADDRESS_IS_EMPTY_OR_INCORRECT("N-521","Source Address is empty or incorrect"),
  SOURCE_NAME_IS_INCORRECT("N-522","Source Name is incorrect"),
  SOURCE_TYPE_IS_EMPTY_OR_INCORRECT("N-523","Source Type is empty or incorrect"),
  DESTINATION_ADDRESS_IS_EMPTY_OR_INCORRECT("N-524","Destination Address is empty or incorrect"),
  DESTINATION_NAME_IS_INCORRECT("N-525","Destination Name is incorrect"),
  DESTINATION_TYPE_IS_EMPTY_OR_INCORRECT("N-526","Destination Type is empty or incorrect"),
  COMMAND_TAG_IS_MISSING("N-527","Command Tag is missing"),
  PARAM_TAG_IS_MISSING("N-528","Param Tag is missing"),
  OBJECTLIST_TAG_IS_MISSING("N-529","ObjectList Tag is missing"),
  OBJECT_TAG_IS_MISSING("N-530","Object Tag is missing"),
  ITEM_TAG_IS_MISSING("N-531","Item Tag is missing"),
  RESULT_TAG_IS_MISSING("N-532","Result Tag is missing"),
  SOURCE_TAG_IS_MISSING("N-533","Source Tag is missing"),
  DESTINATION_TAG_IS_MISSING("N-534","Destination Tag is missing"),
  ONE_OR_MORE_ATTRIBUTE_IS_MISSING_IN_COMMAND_TAG("N-535","One or more attribute is missing in Command Tag"),
  ONE_OR_MORE_ATTRIBUTE_IS_MISSING_IN_PARAM_TAG("N-536","One or more attribute is missing in Param Tag"),
  ONE_OR_MORE_ATTRIBUTE_IS_MISSING_IN_OBJECTLIST_TAG("N-537","One or more attribute is missing in ObjectList Tag"),
  ONE_OR_MORE_ATTRIBUTE_IS_MISSING_IN_OBJECT_TAG("N-538","One or more attribute is missing in Object Tag"),
  ONE_OR_MORE_ATTRIBUTE_IS_MISSING_IN_ITEM_TAG("N-539","One or more attribute is missing in Item Tag"),
  ONE_OR_MORE_ATTRIBUTE_IS_MISSING_IN_RESULT_TAG("N-540","One or more attribute is missing in Result Tag"),
  ONE_OR_MORE_ATTRIBUTE_IS_MISSING_IN_SOURCE_TAG("N-541","One or more attributeis m issing in Source Tag"),
  ONE_OR_MORE_ATTRIBUTE_IS_MISSING_IN_DESTINATION_TAG("N-542","One or more attribute is missing in Destination Tag"),
  VERSION_IS_NOT_ALLOWED_FOR_THE_SERVICE("N-543","Version is not allowed for the service"),
  SOURCE_ADDRESS_IIN_AID_IS_NOT_MATCHING_WITH_SOURCE_TYPE("N-544","Source Address IIN/AID is not matching with Source Type"),
  NETC_REFERENCE_ID_IS_EMPTY_OR_INCORRECT("N-545","Netc Reference Id is empty or incorrect"),
  DESTINATION_ERROR_CODE_IS_EMPTY_OR_INCORRECT("N-546","Destination Error Code is empty or incorrect"),
  NETCREFID_IS_NOT_THERE_IN_DB_OR_NETCREFID_IN_DB_OR_IS_NOT_IN_PENDING_STATE("N-561","NetcRefId is not there in DB or NetcRefId in DB or is Not in Pending State"),
  SOURCE_ID_IIN_AID_DESTINATION_ID_TXN_ID_SHOULD_BE_UNIQUE_FOR_THE_REQUEST("N-562","Source id (IIN/AID) + Destination id (IIN/AID) + Txn id should be unique for the request"),
  TXN_ID_IN_THE_RESPONSE_IS_NOT_MATCHING_WITH_TXN_ID_OF_NETCREFID_IN_DB("N-563","Txn Id in the Response is not Matching with Txn Id of NetcRefId in DB"),
  XML_SCORE_VALUE_IS_NOT_MATCHING_CORRESPONDING_REQUEST_ID_SCORE_VALUE_IN_DB("N-564","XML Score Value is not matching corresponding request id score value in DB"),	  
  GIVEN_COMMAND_ID_IS_NOT_IN_DB("N-565","Given Command Id is Not in DB"),
  COMMAND_NAME_IS_NOT_MATCHED_WITH_DB_VALUE_FOR_THE_GIVEN_COMMAND_ID("N-566","Command Name is Not Matched with DB value for the given Command Id"),
  COMMAND_TYPE_IS_NOT_MATCHED_WITH_DB_VALUE_FOR_THE_GIVEN_COMMAND_ID("N-567","Command Type is Not Matched with DB value for the given Command Id"),
  NUMPARAMS_IS_NOT_MATCHING_WITH_PARAM_COUNT_FOR_THE_COMBINATION_TXN_TYPE("N-568","NumParams is not matching with Param Count for the combination (Command Id + Txn Type)"),
  PARAM_NAME_MISMATCH_WITH_THE_GIVEN_COMMAND_ID_IN_DB("N-569","Param Name mismatch with the given command id in DB"),
  NO_PARAMS_ARE_MAPPED_FOR_THE_GIVEN_COMMAND_ID_TYPE("N-570","No Params are mapped for the given (Command id + type)"),
  OBJECTLIST_IS_NOT_AVAILABLE_FOR_PARAM_TYPE_XML("N-571","ObjectList is not available for Param Type XML"),
  OBJECTS_SIZE_IS_NOT_MATCHING_WITH_NUMOBJECT_VALUE_OR_OBJECT_TAG_IS_NOT_AVAILABLE("N-572","Objects size is not matching with numObject value or Object tag is not available"),
  OBJECT_TYPE_IS_NOT_ARRAY("N-573","Object Type is not ARRAY"),
  ITEM_TYPE_IS_NOT_MATCHING_WITH_THE_DB_VALUE("N-574","Item type is not matching with the DB Value"),
  RESULT_TAG_TIMESTAMP_IS_GREATER_THEN_NETC_SERVER_TIME_STAMP("N-575","Result tag Timestamp is greater then NETC Server time stamp"),
  MESSAGE_NOTAVAILABLE_FOR_CODE576("N-576","message not available for code 576"),
  MESSAGE_NOTAVAILABLE_FOR_CODE577("N-577","message not available for code 577"),
  FOR_TXN_TYPE_RQST_BOTH_SOURCE_DESTINATION_ARE_MATCHING("N-578","For Txn Type RQST, both source & destination are matching"),
  FOR_TXN_TYPE_RQST_DESTINATION_ADDRESS_IS_NOT_MATCHING_WITH_TYPE("N-579","For Txn Type RQST, Destination address is not matching with Type"),
  MESSAGE_NOTAVAILABLE_FOR_CODE580("N-580","message not available for code 580"),
  MESSAGE_NOTAVAILABLE_FOR_CODE581("N-581","message not available for code 581"),
  FOR_TXN_TYPE_RESP_SOURCE_DETAILS_ARE_NOT_MATCHING_WITH_DB_DESTINATION_DETAILS("N-582","For Txn Type RESP, Source details are not matching with DB Destination details"),
  FOR_TXN_TYPE_RESP_DESTINATION_DETAILS_ARE_NOT_MATCHING_WITH_DB_SOURCE_DETAILS("N-583","For Txn Type RESP, Destination details are not matching with DB Source details"),
  NO_OF_ITEMS_MAPPED_IN_DB_IS_NOT_SAME_TO_THE_ITEMS_LIST_IN_THE_MESSAGE("N-584","No. of Items mapped in DB for (Param + Txn Type) is not same to the Items List in the message"),
  NO_ITEMS_ARE_MAPPED_FOR_THE_GIVEN("N-585","No Items are mapped for the given (Param + Txn type)"),
  MESSAGE_NOTAVAILABLE_FOR_CODE586("N-586","message not available for code 586"),
  MESSAGE_NOTAVAILABLE_FOR_CODE587("N-587","message not available for code 587"),
  MESSAGE_NOTAVAILABLE_FOR_CODE588("N-588","message not available for code 588"),
  PARAM_VALUE_PATTERN_IS_NOT_MATCHING_WITH_PARAM_TYPE("N-589","Param Value pattern is not matching with Param Type"),
  PARAM_TYPE_IS_NOT_MATCHING_WITH_CORRESPONDING_PARAM_NAME_IN_THE_DB("N-590","Param Type is not matching with corresponding Param Name in the DB"),
  PARAM_LENGTH_VALUE_IS_NOT_MATCHING_WITH_ITS_VALUE_LENGTH("N-591","Param Length value is not matching with its Value length"),
  ITEM_VALUE_PATTERN_IS_NOT_MATCHING_WITH_ITEM_TYPE("N-592","Item Value pattern is not matching with Item Type"),
  ITEM_LENGTH_VALUE_IS_NOT_MATCHING_WITH_ITS_VALUE_LENGTH("N-593","Item Length value is not matching with its Value length"),
  ITEM_NAME_IS_NOT_MATCHING_WITH_ANY_OF_THE_DB_VALUES_OR_DUPLICATE_ITEM_NAMES("N-594","Item Name is not matching with any of the DB values or duplicate item names"),
  ITEMS_SIZE_IS_NOT_MATCHING_WITH_NUMITEMS_VALUE_OR_ITEM_TAG_IS_NOT_AVAILABLE("N-595","Items size is not matching with numItems value or Item tag is not available"),
  TXN_TIME_IS_AHEAD_OF_TRANSMISSION_TIME("N-596","Txn time is ahead of transmission time"),
  NUMPARAMS_IS_NOT_MATCHING_WITH_PARAM_TAG_SIZE_OF_XML("N-597","NumParams is not matching with Param Tag size of XML"),
  DESTSENTINVALIDRESPONSE("N-600","DestSentInvalidResponse"),
  DESTINATIONISNOTREACHABLE("N-601","DestinationIsNotReachable"),
  INVALIDNETCREFID("N-603","InvalidNetcRefId"),
  INVALID_VIN("N-604","Invalid VIN"),
  INVALID_ENGINE_NUMBER("N-605","Invalid Engine Number"),
  VIN_ENGINE_NUMBER_CANNOT_BE_EMPTY("N-606","VIN/Engine Number cannot be empty"),
  NO_RECORDS_FOUND_FOR_PROVIDED_VIN_AND_ENGINE_NUMBER_COMBINATION("N-607","No records found for provided VIN and Engine Number combination"),
  REGISTERED_VEHICLE_IS_INCORRECT("N-702","Registered Vehicle is incorrect"),
  STATE_IS_EMPTY_OR_INCORRECT("N-703","State is empty or incorrect"),
  TAG_DESCRIPTOR_INCORRECT("N-704","Tag Descriptor incorrect"),
  TAG_DESCRIPTOR_IS_EMPTY("N-705","Tag Descriptor is Empty"),
  TAG_DESCRIPTOR_IS_NOT_IN_DB("N-706","Tag Descriptor is not in DB"),
  STATE_IS_EMPTY("N-707","State is Empty"),
  STATE_IS_NOT_IN_DB("N-708","State is not in DB"),
  VIN_IS_EMPTY("N-709","VIN is Empty"),
  ENGINE_NUMBER_IS_EMPTY("N-710","Engine Number is Empty"),
  REGISTERED_VEHICLE_IS_EMPTY("N-711","Registered Vehicle is Empty"),
  IF_VIN_REGNO_AND_ENGINENUMBER_EXIST_THEN_TAG_DESCRIPTOR_SHOULD_02("N-712","If Vin,RegNo and EngineNumber exist then tag Descriptor should 02"),
  IF_VIN_REGNO_AND_ENGINENUMBER_NOT_EXIST_THEN_TAG_DESCRIPTOR_SHOULD_01("N-713","If Vin,RegNo and EngineNumber not exist then tag Descriptor should 01"),
  EXCEPTION_CODE_IS_NULL_OR_INVALID_FOR_IHMCL_TAGS("N-714","Exception code is null or invalid for IHMCL Tags"),
  SAME_VIN_OR_ENGINENUMBER_OR_REQNO_ALREADY_EXIST("N-715","Same Vin or EngineNumber or ReqNo already exist"),
  PARTICIPANT_NOT_ALLOWED_TO_REGISTER_IHMCL_TAGS("N-716","Participant not allowed to register IHMCL tags"),
  IIN_IN_TAG_ID_IS_NOT_MATCHING_IHMCL_IIN("N-717","IIN in Tag ID is not matching IHMCL IIN"),
  EXCEPTION_CODE_NOT_ALLOWED_FOR_IHMCL_TAGS("N-718","Exception code not allowed for IHMCL Tags"),
  TAG_ID_ALREADY_REGISTERED_IN_MAPPER("N-719","Tag ID already registered in Mapper"),
  BANK_IS_NOT_ALLOWED_TO_REGISTER_IHMCL_TAG("N-720","Bank is not allowed to Register IHMCL Tag"),
  IHMCL_TAG_IS_NOT_IN_IHMCL_MASTER("N-721","IHMCL tag is not in IHMCL Master"),
  IHMCL_TID_MISMATCH("N-722","IHMCL TID Mismatch"),
  IHMCL_VEHICLE_CLASS_CODE_MISMATCH("N-723","IHMCL Vehicle Class code Mismatch"),
  IHMCL_VEHICLE_REGN_NUMBER_MISMATCH("N-724","IHMCL Vehicle Regn Number Mismatch"),
  IHMCL_COMMERCIAL_VEHICLE_MISMATCH("N-725","IHMCL Commercial Vehicle Mismatch"),
  IHMCL_TAG_NOT_REGISTERED("N-726","IHMCL Tag not registered"),
  IHMCL_TAG_CANNOT_BE_REGISTERED_WITH_THE_EXCEPTION_CODE_PROVIDED("N-727","IHMCL Tag cannot be registered with the exception code provided"),
  IHMCL_TAG_IS_NOT_IN_DB_IHMCL_TAG_IS_ALREADY_REGISTERED_IN_MAPPER("N-728","IHMCL tag is not in DB(or)IHMCL tag is already registered in Mapper"),
  IHMCL_REGISTERED_TAG_CANNOT_BE_ADDED_WITH_EXEMPTED_CODE("N-729","IHMCL Registered tag cannot be added with exempted code"),
  DEEMED_DECLINED_AS_THE_ISSUER_IS_NOT_REACHABLE("N-800","Deemed Declined as the Issuer is not reachable."),
  IIN_IN_TAG_ID_IS_NOT_MATCHING_ECOM_IHMCL_IIN("N-420","IIN in Tag ID is not matching Ecom IHMCL IIN"),
  ECOM_TAG_ID_SHOULD_BE_IN_BLACKLIST("N-367","Ecom Tag ID should be in BlackList"),
  NO_SUFFICIENT_CONSENT_DETAILS("N-368","No Sufficient Consent Details"),
  TAG_IS_BLACKLISTED_BY_NON_IHMCL_PARTICIPANT("N-369","Tag is BlackListed by non IHMCL Participant"),
  NOT_ABLE_TO_CONTACT_ACQUIRER("N-370","Not able to contact acquirer"),
  RESPONSE_MSGID_IS_NOT_MATCHING_WITH_REQUEST_MSGID("N-371","Response MsgId is not matching with Request MsgId"),
  RESPONSE_TXNID_IS_NOT_MATCHING_WITH_REQUEST_TXNID("N-372","Response TxnId is not matching with Request TxnId"),
  RESPONSE_NOTE_IS_NOT_MATCHING_WITH_REQUEST_NOTE("N-373","Response Note is not matching with Request Note"),
  RESPONSE_ORGTXNID_IS_NOT_MATCHING_WITH_REQUEST_ORGTXNID("N-374","Response OrgTxnId is not matching with Request OrgTxnId"),
  RESPONSE_REFID_IS_NOT_MATCHING_WITH_REQUEST_REFID("N-375","Response RefId is not matching with Request RefId"),
  RESPONSE_TYPE_IS_NOT_MATCHING_WITH_REQUEST_TYPE("N-376","Response Type is not matching with Request Type"),
  IF_STATUS_IS_Y_THEN_RESPCODE_SHOULD_BE_000("N-377","If status is Y then respcode should be 000"),
  STATUS_SHOULD_BE_Y_OR_N("N-378","Status should be Y or N"),
  NO_CONSENTDETAILS_TAG_IS_PRESENT("N-379","No consentDetails tag is present"),
  SOME_ATTRIBUTE_IS_MISSING_IN_CONSENTDETAILS_TAG("N-380","Some attribute is missing in ConsentDetails tag"),
  ISSUER_NOT_RESPONDED_WITH_IN_SLA("N-381","Issuer not responded with in SLA"),
  NPCI_REF_ID_ATTRIBUTE_IS_MISSING("N-382","NPCI Ref ID attribute is missing"),
  NPCI_REF_ID_NOT_AVAILIBLE_IN_DATABASE_OR_NOT_ASSOCIATED_WITH_THIS_PARTICIPANT("N-383","NPCI Ref Id Not Available in DataBase or not Associated with this participant"),
  NPCI_REF_ID_IS__SHOULD_NOT_BE_EMPTY_OR_NOT_AS_PER_FORMAT("N-384","NPCI Ref ID is  should not be empty or not as per format"),
  MISSING_VEHICLE_CLASS("N-385","Missing vehicle class"),
  NO_TRANSACTION_TRANSACTION("N-387", "No Transaction found"),
  FAILED_TO_FETCH_TAG_DETAILS("N-388","Failed to fetch Tag Details"),
  FAILED_TO_FETCH_TOLL_REGISTRATION("N-389","Failed to fetch Toll Registration details"),
  FAILED_TO_UPDATE_TOLL_REGISTRATION("N-390","Failed to update Toll Registration details"),
  TAG_IS_CLOSED_OR_REPLACED("N-391","Failed to update tag, it's already closed or replaced"),
  FAILED_TO_UPDATE_TAG_IN_INVALID_CARRIAGE("N-392","Failed to update Tag in Invalid Carriage, it's already exist in Exempted state"),
  FAILED_TO_UPDATE_TAG_IN_EXCEPTED_LIST("N-393","Failed to update tag in excepted list, it already exists in Invalid carriages state"),
  FAILED_TO_DELETE_TAG("N-394","Failed to delete Tag, it's already present in one or more exception code"),
  DUPLICATE_REGISTRATION_ON_SAME_DAY("N-395","Same vehicle no has been registerd with other bank today, please try again after 24 hrs"),
  TAGS_WITH_VIN_NOT_FOUND("N-396","No Tags found which is Linked with VIN in given Time range"),
  CREDIT_AMOUNT_DONE("N-397","Credit Amount Done"),
  DEBIT_AMOUNT_DONE("N-398","Debit Amount Done"),
  NETC_NPCI_SERVER_UP("N-399","NETC Server is UP"),
  NETC_NPCI_SERVER_DOWN("N-400","NETC NPCI Server is DOWN"),
  FAILED_TO_ADD_NETC_RESPONSE("N-401","Failed to add NETC Details"),
  RECEIVED_FAILURE_RESPONSE_FROM_NPCI("N-402","Received Failure Response From NPCI"),
  STATE_IS_NOT_IN_DATABASE("N-806","State is not In DB"),
  VIN_IS_EMPTY1("N-811", "VIN Is empty");
  //@formatter:on

  private static final Logger LOG = LogManager.getLogger(HeaderCode.class);

  private String apicode;
  private String message;

  private HeaderCode(String apicode, String message) {
    this.apicode = apicode;
    this.message = message;
  }

  public String code() {
    return this.apicode;
  }

  public String message() {
    return this.message;
  }

  static {
    Set<String> lookup = new HashSet<>();
    for (HeaderCode header : HeaderCode.values()) {
      if (lookup.contains(header.code())) {
        LOG.error(String.format("Duplicate code: %s configured. Last instance will be used",
            header.code()));
      } else {
        lookup.add(header.code());
      }
    }
  }
}
