spring.application.name=osta-api-fastag-module
server.port=6443
server.servlet.context-path=/
server.ssl.enabled=false
spring.main.allow-bean-definition-overriding=true

# Profiles
spring.profiles.active=dev

# Logging
logging.level.root=INFO
logging.level.javax.net.ssl=INFO
logging.level.org.springframework=INFO

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.output.ansi.enabled=always

# Banner
spring.main.banner-mode=console

####################### ACTUATOR CONFIGURATION #######################
management.server.port=6000
management.server.servlet.context-path=/api/v1/customer/fastag
management.endpoints.web.base-path=/actuator
management.server.ssl.enabled=false
management.server.add-application-context-header=true

management.endpoints.web.exposure.include=*
management.endpoints.web.exposure.exclude=beans
management.endpoints.jmx.exposure.include=health,info

management.endpoint.health.show-details=always
management.endpoint.health.show-components=always
management.endpoint.health.probes.enabled=true
management.endpoint.health.group.liveness.include=livenessState
management.endpoint.health.group.readiness.include=readinessState,db,redis

management.health.defaults.enabled=true
management.health.db.enabled=true
management.health.redis.enabled=true
management.health.diskspace.enabled=true
management.health.diskspace.threshold=10MB
management.health.ping.enabled=true
management.health.mail.enabled=false
management.health.jms.enabled=false

management.info.build.enabled=true
management.info.env.enabled=true
management.info.git.enabled=true
management.info.java.enabled=true
management.info.os.enabled=true

info.app.name=${spring.application.name}
info.app.description=OSTA Fastag Module API
info.app.version=0.0.1-SNAPSHOT
info.app.encoding=UTF-8
info.app.java.version=13

management.endpoint.beans.cache.time-to-live=10s
management.endpoint.shutdown.enabled=true
management.endpoint.env.enabled=true
management.endpoint.heapdump.enabled=true
management.endpoint.httptrace.enabled=true
management.endpoint.metrics.enabled=true
management.endpoint.prometheus.enabled=true

management.metrics.export.prometheus.enabled=true
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.metrics.distribution.sla.http.server.requests=100ms,500ms,1s,5s,10s
management.metrics.web.server.requests-metric-name=api.requests

## OAuth2 Resource Server / JWT
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:7443/api/v1/customer/user/.well-known/jwks.json
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:7443/

# Redis Configuration (Optional but helpful to avoid future placeholder issues)
com.dipcoin.db.services.redis.host = localhost
com.dipcoin.db.services.redis.port = 6379
com.dipcoin.db.services.redis.password = 


####################### APPLICATION COMMON PROPERTIES #####################
com.dipcoin.api.config.ApplicationProperties.app.version=0.0.1-SNAPSHOT
com.dipcoin.api.config.ApplicationProperties.app.name=osta-api-fastag-module
com.dipcoin.api.config.ApplicationProperties.blacklistedApis=''
com.dipcoin.api.config.ApplicationProperties.blacklistedHours=0:0
com.dipcoin.api.config.ApplicationProperties.blacklistedApisBank =/v1/customer/osta_DELETE
com.dipcoin.api.config.ApplicationProperties.blacklistedHoursBank = 0:3
com.dipcoin.api.config.ApplicationProperties.senderEmail=alerts-donotreply@ostaapp.com
com.dipcoin.api.config.ApplicationProperties.contactEmail=contact@ostaapp.com
com.dipcoin.api.config.ApplicationProperties.enableSMS=false
com.dipcoin.api.config.ApplicationProperties.androidAppLink=https://play.google.com/store/apps/details?id=com.osta.customer&hl=en_IN
com.dipcoin.api.config.ApplicationProperties.iosAppLink =https://apps.apple.com/app/ostaapp-recharge-bill-pay/id1481060557
com.dipcoin.api.config.ApplicationSecurity.prometheusUser=prometheus
com.dipcoin.api.config.ApplicationSecurity.prometheusPass=mcOnaIqXFHfUxYUhpwW1vXyp+1o8Wiky6BggH4O+wrw=
com.dipcoin.api.config.ApplicationSecurity.adminUser=admin
com.dipcoin.api.config.ApplicationSecurity.adminPass=mcOnaIqXFHfUxYUhpwW1vXyp+1o8Wiky6BggH4O+wrw=

com.dipcoin.api.config.ApplicationProperties.ostaAddress={"company":"Brontoo Technology Solutions ", "name":"India Private Limited", "address":"Avior Corporate Park Nirnal Galaxy ", "street":"L.B.S. Marg Mulund West", "city":"Mumbai - 400080", "email":"Email:contact@ostaapp.com"}
com.dipcoin.api.config.ApplicationProperties.footerMessage=This is a computer generated statement and does not require a signature.

cloud.aws.stack.auto = false 
cloud.aws.region.auto=false
cloud.aws.region.static=ap-south-1

com.dipcoin.api.config.ApplicationProperties.fastagReconAccounting=1002001003,8999801126,9872709870
com.dipcoin.api.config.ApplicationProperties.generatedipcoin.numberOfRetry=50

com.dipcoin.google.recaptcha.key.secret=6LeJEp8pAAAAAKYYrVaoaQLottzcAonfJ3WPDhZj

####################### PAYMENT GATEWAY PROPERTIES #####################
# Paytm Configuration
com.dipcoin.partner.paymentGateway.utils.PaymentGatewayProperties.paytmMerchantId=chuZON47688322129877
com.dipcoin.partner.paymentGateway.utils.PaymentGatewayProperties.paytmMerchantKey=7iD4cYu9U5rFZI2Z
com.dipcoin.partner.paymentGateway.utils.PaymentGatewayProperties.paytmRefundUrl=https://securegw-stage.paytm.in/refund/apply
com.dipcoin.partner.paymentGateway.utils.PaymentGatewayProperties.paytmTransactionStatusUrl=https://securegw-stage.paytm.in/order/status
com.dipcoin.partner.paymentGateway.utils.PaymentGatewayProperties.paytmRefundStatusUrl=https://securegw-stage.paytm.in/v2/refund/status

# OSTA Configuration
com.dipcoin.partner.paymentGateway.utils.PaymentGatewayProperties.ostaOauthUrl=https://api-stage.ostaapp.com/api/v1/oauth2/token
com.dipcoin.partner.paymentGateway.utils.PaymentGatewayProperties.ostaAddMoneyUrl=https://api-stage.ostaapp.com/api/v1/oauth2/addMoney/user

# PayPal Configuration
com.dipcoin.partner.paymentGateway.utils.PaymentGatewayProperties.paypalClientId=AS6Rxfon1oULw5dpERLycjHuuiOcCjeb3536qFJ9IyjVr4QdyRFXKgzhA2zLkZjIzFJqvHOuQG9vMQ4m
com.dipcoin.partner.paymentGateway.utils.PaymentGatewayProperties.paypalSecret=EI24rVaHiK7a2uRAV0pvi1BvSXLVPdjVc1j99GHxYSy3MmPILokm03DmZTjD3Nis-sN4jcmf4PIeMh4y
com.dipcoin.partner.paymentGateway.utils.PaymentGatewayProperties.paypalGetOauthTokenUrl=https://api.sandbox.paypal.com/v1/oauth2/token
com.dipcoin.partner.paymentGateway.utils.PaymentGatewayProperties.paypalCreateOrderReq=https://api.sandbox.paypal.com/v2/checkout/orders
com.dipcoin.partner.paymentGateway.utils.PaymentGatewayProperties.paypalSTCPutReq=https://api.sandbox.paypal.com/v1/risk/transaction-contexts/6Z9AEGM7EPP8Q/trackingId
com.dipcoin.partner.paymentGateway.utils.PaymentGatewayProperties.paypalTransactionStatusUrl=https://api.sandbox.paypal.com/v2/checkout/orders/

# Proxy Configuration
com.dipcoin.partner.paymentGateway.utils.PaymentGatewayProperties.isProxyEnabled=false
com.dipcoin.partner.paymentGateway.utils.PaymentGatewayProperties.port=0
com.dipcoin.partner.paymentGateway.utils.PaymentGatewayProperties.ip=

# Transaction URLs
com.dipcoin.partner.paymentGateway.utils.PaymentGatewayProperties.getTxnStatusUrl=https://localhost:7443/api/v1/oauth2/transactions/status
com.dipcoin.partner.paymentGateway.utils.PaymentGatewayProperties.bankCallBackUrl=https://localhost:8443/api/v1/oauth2/customer/bank/callBackUrl
com.dipcoin.partner.paymentGateway.utils.PaymentGatewayProperties.partnerRefundInitiate=https://api-test.ostaapp.com:7443/api/v1/merchant/refund

# Aggrepay Configuration
com.dipcoin.partner.paymentGateway.utils.PaymentGatewayProperties.aggrepayPaymentSeamlessUrl=https://biz.aggrepaypayments.com/v2/paymentseamlessrequest
com.dipcoin.partner.paymentGateway.utils.PaymentGatewayProperties.aggrepayCheckTransactionStatusUrl=https://biz.aggrepaypayments.com/v2/paymentstatus
com.dipcoin.partner.paymentGateway.utils.PaymentGatewayProperties.aggrepayRefundUrl=https://biz.aggrepaypayments.com/v2/refundrequest

# SMS Lane Settings
com.dipcoin.commons.CommonsProperties.smsClient.connect=true
com.dipcoin.commons.SmsClient.smsBulkUrl=http://103.205.66.77/api/SmsApi/SendSingleUnicodeApi
com.dipcoin.commons.SmsClient.user=ostaapp
com.dipcoin.commons.SmsClient.password=tiln7755TI
com.dipcoin.commons.SmsClient.sid=MYOSTA
com.dipcoin.commons.SesEmailClient.sesRegion=us-east-1
