com.dipcoin.amqp.RabbitMqConfiguration.hostname=localhost
com.dipcoin.amqp.RabbitMqConfiguration.user=guest
com.dipcoin.amqp.RabbitMqConfiguration.password=guest
com.dipcoin.amqp.RabbitMqConfiguration.vhost=/

spring.rabbitmq.listener.enabled=false
spring.rabbitmq.listener.simple.auto-startup=false
spring.rabbitmq.listener.direct.auto-startup=false
spring.rabbitmq.dynamic=false


com.dipcoin.api.config.ApplicationProperties.uiServingHostPort = http://localhost:4200
com.dipcoin.api.config.ApplicationProperties.verifySubuserUrl = /user/forgotpassword
com.dipcoin.api.config.ApplicationProperties.adminVerifySubuserUrl = /user/admin/forgotpassword
com.dipcoin.api.config.ApplicationProperties.uploadFileToS3 = false
com.dipcoin.api.config.ApplicationProperties.logoImgPath = /imgs/home-page/logo-purp.png
com.dipcoin.api.config.ApplicationProperties.mailImgPath = /imgs/mail.png
com.dipcoin.api.config.ApplicationProperties.oauth2EncryptionKey=superrandomstring
com.dipcoin.api.config.ApplicationProperties.ostaRedirectUrl= https://test.ostaapp.com/ostaGateway
com.dipcoin.api.config.ApplicationProperties.deleteWallet= false
com.dipcoin.api.config.ApplicationProperties.offlineApi.job = http://localhost:8080/offline/schedule/job
com.dipcoin.api.config.ApplicationProperties.offlineApi.uploadFile = http://localhost:8080/offline/schedule/uploadFile
com.dipcoin.api.config.ApplicationProperties.sdkRedirectUrl= https://stage.ostaapp.com/user/register/tnc
com.dipcoin.api.config.ApplicationProperties.webUrl= https://stage.ostaapp.com/user/login
com.dipcoin.api.config.ApplicationProperties.appUrl= https://play.google.com/store/apps/details?id=com.osta.customer
com.dipcoin.api.config.ApplicationProperties.localPath=E:/
com.dipcoin.api.config.ApplicationProperties.webUrl.otp= https://www.ostaapp.com/user/register/verify/otp
com.dipcoin.api.config.ApplicationProperties.senderEmail=alerts-donotreply@ostaapp.com
com.dipcoin.api.config.ApplicationProperties.sendBulkTollTagDeletionStatusSheetMailTo=


com.dipcoin.api.config.ApplicationProperties.fraudMgmt = false
com.dipcoin.api.config.ApplicationProperties.awsSMSClient = true
com.dipcoin.api.config.ApplicationProperties.runAudit = true

com.dipcoin.commons.metrics.Metrics.appName=fastag-api

com.dipcoin.commons.metrics.Metrics.publishTimeInSeconds=30

server.ssl.key-store-password = SelfSigned
server.ssl.key-store = classpath:dipcoin-dev.p12
server.ssl.key-store-type = PKCS12
server.ssl.key-alias = selfsigned

com.dipcoin.api.config.ApplicationSecurity.prometheusUser = prometheus
com.dipcoin.api.config.ApplicationSecurity.prometheusPass = password
com.dipcoin.api.config.ApplicationSecurity.adminUser = admin
com.dipcoin.api.config.ApplicationSecurity.adminPass = password


com.dipcoin.api.commons.APIFeatureFlags.Flags.EnableNotification = false

com.dipcoin.api.config.ApplicationProperties.awsSMSClient = true
# AWS SES Email Client Configuration
com.dipcoin.commons.SesEmailClient.sesRegion=us-east-1

com.dipcoin.commons.AwsS3Service.awsAccessKeyId=AKIA6QIVE5D5YGUHA6FJ
com.dipcoin.commons.AwsS3Service.awsSecretAccessKey=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
com.dipcoin.commons.email.restricted.domain=@contact.ostaapp.com,@co.in
com.dipcoin.commons.CommonsProperties.awsS3Bucket = 
com.dipcoin.commons.CommonsProperties.awsS3Region =ap-south-1
com.dipcoin.commons.CommonsProperties.smsClient.connect = false
com.dipcoin.commons.CommonsProperties.emailClient.connect = false
